#ifndef PNTRC_SUB_GEN_H                       /* ----- reinclude-protection ----- */
#define PNTRC_SUB_GEN_H

#ifdef __cplusplus                       /* If C++ - compiler: Use C linkage */
extern "C"
{
#endif

/*****************************************************************************/
/*  Copyright (C) SIEMENS AG                           All rights reserved.  */
/*****************************************************************************/
/*           AUTOGENERATED CODE ---- DO NOT DELETE                           */
/*****************************************************************************/
/*=============================================================================
 * (1) ltrc_subsys
 *===========================================================================*/
#ifndef PNTRC_CFG_SUBSYSTEMS_DEFINED_EXTERNAL
enum ltrc_subsys
{
  TRACE_SUBSYS_TRACE,
  
  TRACE_SUBSYS_ACP_UPPER,
  TRACE_SUBSYS_ACP_RTA = TRACE_SUBSYS_ACP_UPPER + 17,
  TRACE_SUBSYS_ACP_MEM = TRACE_SUBSYS_ACP_RTA + 17,
  TRACE_SUBSYS_ACP_LOWER = TRACE_SUBSYS_ACP_MEM + 17,
  TRACE_SUBSYS_CLRPC_LOWER = TRACE_SUBSYS_ACP_LOWER + 17,
  TRACE_SUBSYS_CLRPC_EPM = TRACE_SUBSYS_CLRPC_LOWER + 17,
  TRACE_SUBSYS_CLRPC_SV_PKT = TRACE_SUBSYS_CLRPC_EPM + 17,
  TRACE_SUBSYS_CLRPC_SV = TRACE_SUBSYS_CLRPC_SV_PKT + 17,
  TRACE_SUBSYS_CLRPC_CL_PKT = TRACE_SUBSYS_CLRPC_SV + 17,
  TRACE_SUBSYS_CLRPC_CL = TRACE_SUBSYS_CLRPC_CL_PKT + 17,
  TRACE_SUBSYS_CLRPC_UPPER = TRACE_SUBSYS_CLRPC_CL + 17,
  TRACE_SUBSYS_CM_UPPER = TRACE_SUBSYS_CLRPC_UPPER + 17,
  TRACE_SUBSYS_CM_SV = TRACE_SUBSYS_CM_UPPER + 17,
  TRACE_SUBSYS_CM_RPC = TRACE_SUBSYS_CM_SV + 17,
  TRACE_SUBSYS_CM_POF = TRACE_SUBSYS_CM_RPC + 17,
  TRACE_SUBSYS_CM_PD = TRACE_SUBSYS_CM_POF + 17,
  TRACE_SUBSYS_CM_OHA = TRACE_SUBSYS_CM_PD + 17,
  TRACE_SUBSYS_CM_NARE = TRACE_SUBSYS_CM_OHA + 17,
  TRACE_SUBSYS_CM_MRP = TRACE_SUBSYS_CM_NARE + 17,
  TRACE_SUBSYS_CM_MEM = TRACE_SUBSYS_CM_MRP + 17,
  TRACE_SUBSYS_CM_MC = TRACE_SUBSYS_CM_MEM + 17,
  TRACE_SUBSYS_CM_GSY = TRACE_SUBSYS_CM_MC + 17,
  TRACE_SUBSYS_CM_EDD = TRACE_SUBSYS_CM_GSY + 17,
  TRACE_SUBSYS_CM_CL = TRACE_SUBSYS_CM_EDD + 17,
  TRACE_SUBSYS_CM_AR = TRACE_SUBSYS_CM_CL + 17,
  TRACE_SUBSYS_CM_ACP = TRACE_SUBSYS_CM_AR + 17,
  TRACE_SUBSYS_DCP_UPPER = TRACE_SUBSYS_CM_ACP + 17,
  TRACE_SUBSYS_DCP_SYSTEM = TRACE_SUBSYS_DCP_UPPER + 17,
  TRACE_SUBSYS_DCP_SRVERR = TRACE_SUBSYS_DCP_SYSTEM + 17,
  TRACE_SUBSYS_DCP_SNDRCV = TRACE_SUBSYS_DCP_SRVERR + 17,
  TRACE_SUBSYS_DCP_SERVER = TRACE_SUBSYS_DCP_SNDRCV + 17,
  TRACE_SUBSYS_DCP_LOWER = TRACE_SUBSYS_DCP_SERVER + 17,
  TRACE_SUBSYS_DCP_FUNCTION = TRACE_SUBSYS_DCP_LOWER + 17,
  TRACE_SUBSYS_DCP_ERROR = TRACE_SUBSYS_DCP_FUNCTION + 17,
  TRACE_SUBSYS_EDDI_PROGRAM = TRACE_SUBSYS_DCP_ERROR + 17,
  TRACE_SUBSYS_EDDI_SYNC = TRACE_SUBSYS_EDDI_PROGRAM + 17,
  TRACE_SUBSYS_EDDI_CRT = TRACE_SUBSYS_EDDI_SYNC + 17,
  TRACE_SUBSYS_EDDI_SWI = TRACE_SUBSYS_EDDI_CRT + 17,
  TRACE_SUBSYS_EDDI_PRM = TRACE_SUBSYS_EDDI_SWI + 17,
  TRACE_SUBSYS_EDDI_NRT = TRACE_SUBSYS_EDDI_PRM + 17,
  TRACE_SUBSYS_EDDI_FUNCTION = TRACE_SUBSYS_EDDI_NRT + 17,
  TRACE_SUBSYS_EDDI_SYSTEM = TRACE_SUBSYS_EDDI_FUNCTION + 17,
  TRACE_SUBSYS_EDDI_LOWER = TRACE_SUBSYS_EDDI_SYSTEM + 17,
  TRACE_SUBSYS_EDDI_UPPER = TRACE_SUBSYS_EDDI_LOWER + 17,
  TRACE_SUBSYS_EDDS_SCHED = TRACE_SUBSYS_EDDI_UPPER + 17,
  TRACE_SUBSYS_EDDS_LL = TRACE_SUBSYS_EDDS_SCHED + 17,
  TRACE_SUBSYS_EDDS_CRT = TRACE_SUBSYS_EDDS_LL + 17,
  TRACE_SUBSYS_EDDS_CORE = TRACE_SUBSYS_EDDS_CRT + 17,
  TRACE_SUBSYS_EDDS_SWI = TRACE_SUBSYS_EDDS_CORE + 17,
  TRACE_SUBSYS_EDDS_PRM = TRACE_SUBSYS_EDDS_SWI + 17,
  TRACE_SUBSYS_EDDS_NRT = TRACE_SUBSYS_EDDS_PRM + 17,
  TRACE_SUBSYS_EDDS_PROGRAM = TRACE_SUBSYS_EDDS_NRT + 17,
  TRACE_SUBSYS_EDDS_FUNCTION = TRACE_SUBSYS_EDDS_PROGRAM + 17,
  TRACE_SUBSYS_EDDS_SYSTEM = TRACE_SUBSYS_EDDS_FUNCTION + 17,
  TRACE_SUBSYS_EDDS_LOWER = TRACE_SUBSYS_EDDS_SYSTEM + 17,
  TRACE_SUBSYS_EDDS_UPPER = TRACE_SUBSYS_EDDS_LOWER + 17,
  TRACE_SUBSYS_EPS_SYSTEM = TRACE_SUBSYS_EDDS_UPPER + 17,
  TRACE_SUBSYS_GSY_DIAG = TRACE_SUBSYS_EPS_SYSTEM + 17,
  TRACE_SUBSYS_GSY_PRM = TRACE_SUBSYS_GSY_DIAG + 17,
  TRACE_SUBSYS_GSY_SNDRCV = TRACE_SUBSYS_GSY_PRM + 17,
  TRACE_SUBSYS_GSY_FWD = TRACE_SUBSYS_GSY_SNDRCV + 17,
  TRACE_SUBSYS_GSY_DEL = TRACE_SUBSYS_GSY_FWD + 17,
  TRACE_SUBSYS_GSY_SYNC = TRACE_SUBSYS_GSY_DEL + 17,
  TRACE_SUBSYS_GSY_MASTER = TRACE_SUBSYS_GSY_SYNC + 17,
  TRACE_SUBSYS_GSY_ERROR = TRACE_SUBSYS_GSY_MASTER + 17,
  TRACE_SUBSYS_GSY_FUNCTION = TRACE_SUBSYS_GSY_ERROR + 17,
  TRACE_SUBSYS_GSY_PROTOCOL = TRACE_SUBSYS_GSY_FUNCTION + 17,
  TRACE_SUBSYS_GSY_SYSTEM = TRACE_SUBSYS_GSY_PROTOCOL + 17,
  TRACE_SUBSYS_GSY_MEMORY = TRACE_SUBSYS_GSY_SYSTEM + 17,
  TRACE_SUBSYS_GSY_LOWER = TRACE_SUBSYS_GSY_MEMORY + 17,
  TRACE_SUBSYS_GSY_UPPER = TRACE_SUBSYS_GSY_LOWER + 17,
  TRACE_SUBSYS_HIF_PROGRAM = TRACE_SUBSYS_GSY_UPPER + 17,
  TRACE_SUBSYS_LLDP_UPPER = TRACE_SUBSYS_HIF_PROGRAM + 17,
  TRACE_SUBSYS_LLDP_SYSTEM = TRACE_SUBSYS_LLDP_UPPER + 17,
  TRACE_SUBSYS_LLDP_PROGRAM = TRACE_SUBSYS_LLDP_SYSTEM + 17,
  TRACE_SUBSYS_LLDP_LOWER = TRACE_SUBSYS_LLDP_PROGRAM + 17,
  TRACE_SUBSYS_LLDP_FUNCTION = TRACE_SUBSYS_LLDP_LOWER + 17,
  TRACE_SUBSYS_NARE_UPPER = TRACE_SUBSYS_LLDP_FUNCTION + 17,
  TRACE_SUBSYS_NARE_SYSTEM = TRACE_SUBSYS_NARE_UPPER + 17,
  TRACE_SUBSYS_NARE_PROGRAM = TRACE_SUBSYS_NARE_SYSTEM + 17,
  TRACE_SUBSYS_NARE_LOWER = TRACE_SUBSYS_NARE_PROGRAM + 17,
  TRACE_SUBSYS_NARE_FUNCTION = TRACE_SUBSYS_NARE_LOWER + 17,
  TRACE_SUBSYS_OHA_UPPER = TRACE_SUBSYS_NARE_FUNCTION + 17,
  TRACE_SUBSYS_OHA_SYSTEM = TRACE_SUBSYS_OHA_UPPER + 17,
  TRACE_SUBSYS_OHA_PROGRAM = TRACE_SUBSYS_OHA_SYSTEM + 17,
  TRACE_SUBSYS_OHA_LOWER = TRACE_SUBSYS_OHA_PROGRAM + 17,
  TRACE_SUBSYS_OHA_FUNCTION = TRACE_SUBSYS_OHA_LOWER + 17,
  TRACE_SUBSYS_PNTRC_SYSTEM = TRACE_SUBSYS_OHA_FUNCTION + 17,
  TRACE_SUBSYS_PSI_HD = TRACE_SUBSYS_PNTRC_SYSTEM + 17,
  TRACE_SUBSYS_PSI_LD = TRACE_SUBSYS_PSI_HD + 17,
  TRACE_SUBSYS_PSI_SYSTEM = TRACE_SUBSYS_PSI_LD + 17,
  TRACE_SUBSYS_SNMPX_UPPER = TRACE_SUBSYS_PSI_SYSTEM + 17,
  TRACE_SUBSYS_SNMPX_SYSTEM = TRACE_SUBSYS_SNMPX_UPPER + 17,
  TRACE_SUBSYS_SNMPX_PROGRAM = TRACE_SUBSYS_SNMPX_SYSTEM + 17,
  TRACE_SUBSYS_SNMPX_LOWER = TRACE_SUBSYS_SNMPX_PROGRAM + 17,
  TRACE_SUBSYS_SNMPX_MEMORY = TRACE_SUBSYS_SNMPX_LOWER + 17,
  TRACE_SUBSYS_SNMPX_PROTOCOL = TRACE_SUBSYS_SNMPX_MEMORY + 17,
  TRACE_SUBSYS_SNMPX_FUNCTION = TRACE_SUBSYS_SNMPX_PROTOCOL + 17,
  TRACE_SUBSYS_SOCK_UPPER = TRACE_SUBSYS_SNMPX_FUNCTION + 17,
  TRACE_SUBSYS_SOCK_SYSTEM = TRACE_SUBSYS_SOCK_UPPER + 17,
  TRACE_SUBSYS_SOCK_PROTOCOL = TRACE_SUBSYS_SOCK_SYSTEM + 17,
  TRACE_SUBSYS_SOCK_LOWER = TRACE_SUBSYS_SOCK_PROTOCOL + 17,
  TRACE_SUBSYS_TCIP_OBSD = TRACE_SUBSYS_SOCK_LOWER + 17,
  TRACE_SUBSYS_TCIP_INICHE = TRACE_SUBSYS_TCIP_OBSD + 17,
  TRACE_SUBSYS_TCIP_MEM = TRACE_SUBSYS_TCIP_INICHE + 17,
  TRACE_SUBSYS_TCIP_UPPER = TRACE_SUBSYS_TCIP_MEM + 17,
  TRACE_SUBSYS_PND_SYSTEM = TRACE_SUBSYS_TCIP_UPPER + 17,
  TRACE_SUBSYS_PND_PNUC = TRACE_SUBSYS_PND_SYSTEM + 17,
  TRACE_SUBSYS_PND_IOBC = TRACE_SUBSYS_PND_PNUC + 17,
  TRACE_SUBSYS_PND_AGENT = TRACE_SUBSYS_PND_IOBC + 17,
  TRACE_SUBSYS_PND_PARAMS = TRACE_SUBSYS_PND_AGENT + 17,
  TRACE_SUBSYS_PND_IODU = TRACE_SUBSYS_PND_PARAMS + 17,
  TRACE_SUBSYS_PND_PNTRC = TRACE_SUBSYS_PND_IODU + 17,
  TRACE_SUBSYS_PND_ISO = TRACE_SUBSYS_PND_PNTRC + 17,
  TRACE_SUBSYS_PND_OHA = TRACE_SUBSYS_PND_ISO + 17,
  TRACE_SUBSYS_PND_IOH = TRACE_SUBSYS_PND_OHA + 17,
  TRACE_SUBSYS_PND_IOC = TRACE_SUBSYS_PND_IOH + 17,
  TRACE_SUBSYS_PND_PD = TRACE_SUBSYS_PND_IOC + 17,

  TRACE_SUBSYS_NUM = TRACE_SUBSYS_PND_PD + 17

};
#endif

#define LTRC_SUBSYS_TYPE enum ltrc_subsys

/*=====  components  ====================================*/
enum ltrc_comp {
  TRACE_COMP_ACP,
  TRACE_COMP_CLRPC,
  TRACE_COMP_CM,
  TRACE_COMP_DCP,
  TRACE_COMP_EDDI,
  TRACE_COMP_EDDS,
  TRACE_COMP_EPS,
  TRACE_COMP_GSY,
  TRACE_COMP_HIF,
  TRACE_COMP_LLDP,
  TRACE_COMP_NARE,
  TRACE_COMP_OHA,
  TRACE_COMP_PNTRC,
  TRACE_COMP_PSI,
  TRACE_COMP_SNMPX,
  TRACE_COMP_SOCK,
  TRACE_COMP_TCIP,
  TRACE_COMP_PND,

  TRACE_COMP_NUM
};

#define LTRC_COMP_TYPE enum ltrc_comp

/*=====  levels  ====================================*/
enum pntrc_level
{
  PNTRC_TRACE_LEVEL_OFF,
  PNTRC_TRACE_LEVEL_FATAL,
  PNTRC_TRACE_LEVEL_ERROR,
  PNTRC_TRACE_LEVEL_UNEXP,
  PNTRC_TRACE_LEVEL_WARN,
  PNTRC_TRACE_LEVEL_NOTE_HIGH,
  PNTRC_TRACE_LEVEL_NOTE,
  PNTRC_TRACE_LEVEL_NOTE_LOW,
  PNTRC_TRACE_LEVEL_CHAT,

  TRACE_LEVEL_NUM
};
#define PNTRC_LEVEL_TYPE enum pntrc_level

#ifndef LTRC_LEVEL_TYPE
#define LTRC_LEVEL_TYPE PNTRC_LEVEL_TYPE
#endif


typedef LSA_VOID (*PNTRC_CB_BUFFER_FULL) (LSA_VOID* Ptr, LSA_UINT8* Buffer, LSA_UINT32 Size);

/*=============================================================================
 * (2) ltrc_subsys_cfg_table
 *===========================================================================*/
 
/* intern admin struct for every subsystem */
typedef  struct {
  LSA_UINT16                    subsysId;
  LSA_UINT16                    instance;
  LSA_CHAR                      name[32];
  LSA_UINT8                     level;
  LTRC_COMP_TYPE        comp;
}LTRC_ADVTEXT_INFO_TYPE;

#if defined LTRC_SET_SUBSYS_CFG_TABLE

const LTRC_ADVTEXT_INFO_TYPE    LSA_CONST_MEM_ATTR
ltrc_subsys_cfg_table [] =
   {

   { TRACE_SUBSYS_TRACE, 1, "[TRACE]" }, 

   { TRACE_SUBSYS_ACP_UPPER,                17, "[ACP_UPPER]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_ACP},
   { TRACE_SUBSYS_ACP_RTA,                  17, "[ACP_RTA]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_ACP},
   { TRACE_SUBSYS_ACP_MEM,                  17, "[ACP_MEM]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_ACP},
   { TRACE_SUBSYS_ACP_LOWER,                17, "[ACP_LOWER]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_ACP},
   { TRACE_SUBSYS_CLRPC_LOWER,              17, "[CLRPC_LOWER]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CLRPC},
   { TRACE_SUBSYS_CLRPC_EPM,                17, "[CLRPC_EPM]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CLRPC},
   { TRACE_SUBSYS_CLRPC_SV_PKT,             17, "[CLRPC_SV_PKT]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CLRPC},
   { TRACE_SUBSYS_CLRPC_SV,                 17, "[CLRPC_SV]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CLRPC},
   { TRACE_SUBSYS_CLRPC_CL_PKT,             17, "[CLRPC_CL_PKT]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CLRPC},
   { TRACE_SUBSYS_CLRPC_CL,                 17, "[CLRPC_CL]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CLRPC},
   { TRACE_SUBSYS_CLRPC_UPPER,              17, "[CLRPC_UPPER]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CLRPC},
   { TRACE_SUBSYS_CM_UPPER,                 17, "[CM_UPPER]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_SV,                    17, "[CM_SV]",                PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_RPC,                   17, "[CM_RPC]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_POF,                   17, "[CM_POF]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_PD,                    17, "[CM_PD]",                PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_OHA,                   17, "[CM_OHA]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_NARE,                  17, "[CM_NARE]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_MRP,                   17, "[CM_MRP]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_MEM,                   17, "[CM_MEM]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_MC,                    17, "[CM_MC]",                PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_GSY,                   17, "[CM_GSY]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_EDD,                   17, "[CM_EDD]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_CL,                    17, "[CM_CL]",                PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_AR,                    17, "[CM_AR]",                PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_CM_ACP,                   17, "[CM_ACP]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_CM},
   { TRACE_SUBSYS_DCP_UPPER,                17, "[DCP_UPPER]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_DCP},
   { TRACE_SUBSYS_DCP_SYSTEM,               17, "[DCP_SYSTEM]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_DCP},
   { TRACE_SUBSYS_DCP_SRVERR,               17, "[DCP_SRVERR]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_DCP},
   { TRACE_SUBSYS_DCP_SNDRCV,               17, "[DCP_SNDRCV]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_DCP},
   { TRACE_SUBSYS_DCP_SERVER,               17, "[DCP_SERVER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_DCP},
   { TRACE_SUBSYS_DCP_LOWER,                17, "[DCP_LOWER]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_DCP},
   { TRACE_SUBSYS_DCP_FUNCTION,             17, "[DCP_FUNCTION]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_DCP},
   { TRACE_SUBSYS_DCP_ERROR,                17, "[DCP_ERROR]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_DCP},
   { TRACE_SUBSYS_EDDI_PROGRAM,             17, "[EDDI_PROGRAM]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_SYNC,                17, "[EDDI_SYNC]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_CRT,                 17, "[EDDI_CRT]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_SWI,                 17, "[EDDI_SWI]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_PRM,                 17, "[EDDI_PRM]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_NRT,                 17, "[EDDI_NRT]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_FUNCTION,            17, "[EDDI_FUNCTION]",        PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_SYSTEM,              17, "[EDDI_SYSTEM]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_LOWER,               17, "[EDDI_LOWER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDI_UPPER,               17, "[EDDI_UPPER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDI},
   { TRACE_SUBSYS_EDDS_SCHED,               17, "[EDDS_SCHED]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_LL,                  17, "[EDDS_LL]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_CRT,                 17, "[EDDS_CRT]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_CORE,                17, "[EDDS_CORE]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_SWI,                 17, "[EDDS_SWI]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_PRM,                 17, "[EDDS_PRM]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_NRT,                 17, "[EDDS_NRT]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_PROGRAM,             17, "[EDDS_PROGRAM]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_FUNCTION,            17, "[EDDS_FUNCTION]",        PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_SYSTEM,              17, "[EDDS_SYSTEM]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_LOWER,               17, "[EDDS_LOWER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EDDS_UPPER,               17, "[EDDS_UPPER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EDDS},
   { TRACE_SUBSYS_EPS_SYSTEM,               17, "[EPS_SYSTEM]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_EPS},
   { TRACE_SUBSYS_GSY_DIAG,                 17, "[GSY_DIAG]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_PRM,                  17, "[GSY_PRM]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_SNDRCV,               17, "[GSY_SNDRCV]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_FWD,                  17, "[GSY_FWD]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_DEL,                  17, "[GSY_DEL]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_SYNC,                 17, "[GSY_SYNC]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_MASTER,               17, "[GSY_MASTER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_ERROR,                17, "[GSY_ERROR]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_FUNCTION,             17, "[GSY_FUNCTION]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_PROTOCOL,             17, "[GSY_PROTOCOL]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_SYSTEM,               17, "[GSY_SYSTEM]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_MEMORY,               17, "[GSY_MEMORY]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_LOWER,                17, "[GSY_LOWER]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_GSY_UPPER,                17, "[GSY_UPPER]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_GSY},
   { TRACE_SUBSYS_HIF_PROGRAM,              17, "[HIF_PROGRAM]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_HIF},
   { TRACE_SUBSYS_LLDP_UPPER,               17, "[LLDP_UPPER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_LLDP},
   { TRACE_SUBSYS_LLDP_SYSTEM,              17, "[LLDP_SYSTEM]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_LLDP},
   { TRACE_SUBSYS_LLDP_PROGRAM,             17, "[LLDP_PROGRAM]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_LLDP},
   { TRACE_SUBSYS_LLDP_LOWER,               17, "[LLDP_LOWER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_LLDP},
   { TRACE_SUBSYS_LLDP_FUNCTION,            17, "[LLDP_FUNCTION]",        PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_LLDP},
   { TRACE_SUBSYS_NARE_UPPER,               17, "[NARE_UPPER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_NARE},
   { TRACE_SUBSYS_NARE_SYSTEM,              17, "[NARE_SYSTEM]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_NARE},
   { TRACE_SUBSYS_NARE_PROGRAM,             17, "[NARE_PROGRAM]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_NARE},
   { TRACE_SUBSYS_NARE_LOWER,               17, "[NARE_LOWER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_NARE},
   { TRACE_SUBSYS_NARE_FUNCTION,            17, "[NARE_FUNCTION]",        PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_NARE},
   { TRACE_SUBSYS_OHA_UPPER,                17, "[OHA_UPPER]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_OHA},
   { TRACE_SUBSYS_OHA_SYSTEM,               17, "[OHA_SYSTEM]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_OHA},
   { TRACE_SUBSYS_OHA_PROGRAM,              17, "[OHA_PROGRAM]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_OHA},
   { TRACE_SUBSYS_OHA_LOWER,                17, "[OHA_LOWER]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_OHA},
   { TRACE_SUBSYS_OHA_FUNCTION,             17, "[OHA_FUNCTION]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_OHA},
   { TRACE_SUBSYS_PNTRC_SYSTEM,             17, "[PNTRC_SYSTEM]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PNTRC},
   { TRACE_SUBSYS_PSI_HD,                   17, "[PSI_HD]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PSI},
   { TRACE_SUBSYS_PSI_LD,                   17, "[PSI_LD]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PSI},
   { TRACE_SUBSYS_PSI_SYSTEM,               17, "[PSI_SYSTEM]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PSI},
   { TRACE_SUBSYS_SNMPX_UPPER,              17, "[SNMPX_UPPER]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SNMPX},
   { TRACE_SUBSYS_SNMPX_SYSTEM,             17, "[SNMPX_SYSTEM]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SNMPX},
   { TRACE_SUBSYS_SNMPX_PROGRAM,            17, "[SNMPX_PROGRAM]",        PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SNMPX},
   { TRACE_SUBSYS_SNMPX_LOWER,              17, "[SNMPX_LOWER]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SNMPX},
   { TRACE_SUBSYS_SNMPX_MEMORY,             17, "[SNMPX_MEMORY]",         PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SNMPX},
   { TRACE_SUBSYS_SNMPX_PROTOCOL,           17, "[SNMPX_PROTOCOL]",       PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SNMPX},
   { TRACE_SUBSYS_SNMPX_FUNCTION,           17, "[SNMPX_FUNCTION]",       PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SNMPX},
   { TRACE_SUBSYS_SOCK_UPPER,               17, "[SOCK_UPPER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SOCK},
   { TRACE_SUBSYS_SOCK_SYSTEM,              17, "[SOCK_SYSTEM]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SOCK},
   { TRACE_SUBSYS_SOCK_PROTOCOL,            17, "[SOCK_PROTOCOL]",        PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SOCK},
   { TRACE_SUBSYS_SOCK_LOWER,               17, "[SOCK_LOWER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_SOCK},
   { TRACE_SUBSYS_TCIP_OBSD,                17, "[TCIP_OBSD]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_TCIP},
   { TRACE_SUBSYS_TCIP_INICHE,              17, "[TCIP_INICHE]",          PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_TCIP},
   { TRACE_SUBSYS_TCIP_MEM,                 17, "[TCIP_MEM]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_TCIP},
   { TRACE_SUBSYS_TCIP_UPPER,               17, "[TCIP_UPPER]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_TCIP},
   { TRACE_SUBSYS_PND_SYSTEM,               17, "[PND_SYSTEM]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_PNUC,                 17, "[PND_PNUC]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_IOBC,                 17, "[PND_IOBC]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_AGENT,                17, "[PND_AGENT]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_PARAMS,               17, "[PND_PARAMS]",           PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_IODU,                 17, "[PND_IODU]",             PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_PNTRC,                17, "[PND_PNTRC]",            PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_ISO,                  17, "[PND_ISO]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_OHA,                  17, "[PND_OHA]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_IOH,                  17, "[PND_IOH]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_IOC,                  17, "[PND_IOC]",              PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_PND_PD,                   17, "[PND_PD]",               PNTRC_CFG_LEVEL_DEFAULT, TRACE_COMP_PND},
   { TRACE_SUBSYS_NUM,                           0xffff, "ENDE-ltrc_subsys_cfg_table-ENDE"   ,PNTRC_CFG_LEVEL_DEFAULT    }
   };
#endif


/*=============================================================================
 * (3) region for ltrcscanner
 *===========================================================================*/
/*|@@@START-LTRC-Scanner-Params@@@|

   TRACE_SUBSYS_TRACE,                   trace;

   TRACE_SUBSYS_ACP_UPPER,              acp\src,       ACP_UPPER,         1;
   TRACE_SUBSYS_ACP_RTA,                acp\src,       ACP_RTA,           1;
   TRACE_SUBSYS_ACP_MEM,                acp\src,       ACP_MEM,           1;
   TRACE_SUBSYS_ACP_LOWER,              acp\src,       ACP_LOWER,         1;
   TRACE_SUBSYS_CLRPC_LOWER,            clrpc\src,     CLRPC_LOWER,       1;
   TRACE_SUBSYS_CLRPC_EPM,              clrpc\src,     CLRPC_EPM,         1;
   TRACE_SUBSYS_CLRPC_SV_PKT,           clrpc\src,     CLRPC_SV_PKT,      1;
   TRACE_SUBSYS_CLRPC_SV,               clrpc\src,     CLRPC_SV,          1;
   TRACE_SUBSYS_CLRPC_CL_PKT,           clrpc\src,     CLRPC_CL_PKT,      1;
   TRACE_SUBSYS_CLRPC_CL,               clrpc\src,     CLRPC_CL,          1;
   TRACE_SUBSYS_CLRPC_UPPER,            clrpc\src,     CLRPC_UPPER,       1;
   TRACE_SUBSYS_CM_UPPER,               cm\src,        CM_UPPER,          1;
   TRACE_SUBSYS_CM_SV,                  cm\src,        CM_SV,             1;
   TRACE_SUBSYS_CM_RPC,                 cm\src,        CM_RPC,            1;
   TRACE_SUBSYS_CM_POF,                 cm\src,        CM_POF,            1;
   TRACE_SUBSYS_CM_PD,                  cm\src,        CM_PD,             1;
   TRACE_SUBSYS_CM_OHA,                 cm\src,        CM_OHA,            1;
   TRACE_SUBSYS_CM_NARE,                cm\src,        CM_NARE,           1;
   TRACE_SUBSYS_CM_MRP,                 cm\src,        CM_MRP,            1;
   TRACE_SUBSYS_CM_MEM,                 cm\src,        CM_MEM,            1;
   TRACE_SUBSYS_CM_MC,                  cm\src,        CM_MC,             1;
   TRACE_SUBSYS_CM_GSY,                 cm\src,        CM_GSY,            1;
   TRACE_SUBSYS_CM_EDD,                 cm\src,        CM_EDD,            1;
   TRACE_SUBSYS_CM_CL,                  cm\src,        CM_CL,             1;
   TRACE_SUBSYS_CM_AR,                  cm\src,        CM_AR,             1;
   TRACE_SUBSYS_CM_ACP,                 cm\src,        CM_ACP,            1;
   TRACE_SUBSYS_DCP_UPPER,              dcp\src,       DCP_UPPER,         1;
   TRACE_SUBSYS_DCP_SYSTEM,             dcp\src,       DCP_SYSTEM,        1;
   TRACE_SUBSYS_DCP_SRVERR,             dcp\src,       DCP_SRVERR,        1;
   TRACE_SUBSYS_DCP_SNDRCV,             dcp\src,       DCP_SNDRCV,        1;
   TRACE_SUBSYS_DCP_SERVER,             dcp\src,       DCP_SERVER,        1;
   TRACE_SUBSYS_DCP_LOWER,              dcp\src,       DCP_LOWER,         1;
   TRACE_SUBSYS_DCP_FUNCTION,           dcp\src,       DCP_FUNCTION,      1;
   TRACE_SUBSYS_DCP_ERROR,              dcp\src,       DCP_ERROR,         1;
   TRACE_SUBSYS_EDDI_PROGRAM,           eddi\src,      EDDI_PROGRAM,      1;
   TRACE_SUBSYS_EDDI_SYNC,              eddi\src,      EDDI_SYNC,         1;
   TRACE_SUBSYS_EDDI_CRT,               eddi\src,      EDDI_CRT,          1;
   TRACE_SUBSYS_EDDI_SWI,               eddi\src,      EDDI_SWI,          1;
   TRACE_SUBSYS_EDDI_PRM,               eddi\src,      EDDI_PRM,          1;
   TRACE_SUBSYS_EDDI_NRT,               eddi\src,      EDDI_NRT,          1;
   TRACE_SUBSYS_EDDI_FUNCTION,          eddi\src,      EDDI_FUNCTION,     1;
   TRACE_SUBSYS_EDDI_SYSTEM,            eddi\src,      EDDI_SYSTEM,       1;
   TRACE_SUBSYS_EDDI_LOWER,             eddi\src,      EDDI_LOWER,        1;
   TRACE_SUBSYS_EDDI_UPPER,             eddi\src,      EDDI_UPPER,        1;
   TRACE_SUBSYS_EDDS_SCHED,             edds\src,      EDDS_SCHED,        1;
   TRACE_SUBSYS_EDDS_LL,                edds\src,      EDDS_LL,           1;
   TRACE_SUBSYS_EDDS_CRT,               edds\src,      EDDS_CRT,          1;
   TRACE_SUBSYS_EDDS_CORE,              edds\src,      EDDS_CORE,         1;
   TRACE_SUBSYS_EDDS_SWI,               edds\src,      EDDS_SWI,          1;
   TRACE_SUBSYS_EDDS_PRM,               edds\src,      EDDS_PRM,          1;
   TRACE_SUBSYS_EDDS_NRT,               edds\src,      EDDS_NRT,          1;
   TRACE_SUBSYS_EDDS_PROGRAM,           edds\src,      EDDS_PROGRAM,      1;
   TRACE_SUBSYS_EDDS_FUNCTION,          edds\src,      EDDS_FUNCTION,     1;
   TRACE_SUBSYS_EDDS_SYSTEM,            edds\src,      EDDS_SYSTEM,       1;
   TRACE_SUBSYS_EDDS_LOWER,             edds\src,      EDDS_LOWER,        1;
   TRACE_SUBSYS_EDDS_UPPER,             edds\src,      EDDS_UPPER,        1;
   TRACE_SUBSYS_EPS_SYSTEM,             pnboards,    EPS_SYSTEM,        1;
   TRACE_SUBSYS_GSY_DIAG,               gsy\src,       GSY_DIAG,          1;
   TRACE_SUBSYS_GSY_PRM,                gsy\src,       GSY_PRM,           1;
   TRACE_SUBSYS_GSY_SNDRCV,             gsy\src,       GSY_SNDRCV,        1;
   TRACE_SUBSYS_GSY_FWD,                gsy\src,       GSY_FWD,           1;
   TRACE_SUBSYS_GSY_DEL,                gsy\src,       GSY_DEL,           1;
   TRACE_SUBSYS_GSY_SYNC,               gsy\src,       GSY_SYNC,          1;
   TRACE_SUBSYS_GSY_MASTER,             gsy\src,       GSY_MASTER,        1;
   TRACE_SUBSYS_GSY_ERROR,              gsy\src,       GSY_ERROR,         1;
   TRACE_SUBSYS_GSY_FUNCTION,           gsy\src,       GSY_FUNCTION,      1;
   TRACE_SUBSYS_GSY_PROTOCOL,           gsy\src,       GSY_PROTOCOL,      1;
   TRACE_SUBSYS_GSY_SYSTEM,             gsy\src,       GSY_SYSTEM,        1;
   TRACE_SUBSYS_GSY_MEMORY,             gsy\src,       GSY_MEMORY,        1;
   TRACE_SUBSYS_GSY_LOWER,              gsy\src,       GSY_LOWER,         1;
   TRACE_SUBSYS_GSY_UPPER,              gsy\src,       GSY_UPPER,         1;
   TRACE_SUBSYS_HIF_PROGRAM,            hif\src,       HIF_PROGRAM,       1;
   TRACE_SUBSYS_LLDP_UPPER,             lldp\src,      LLDP_UPPER,        1;
   TRACE_SUBSYS_LLDP_SYSTEM,            lldp\src,      LLDP_SYSTEM,       1;
   TRACE_SUBSYS_LLDP_PROGRAM,           lldp\src,      LLDP_PROGRAM,      1;
   TRACE_SUBSYS_LLDP_LOWER,             lldp\src,      LLDP_LOWER,        1;
   TRACE_SUBSYS_LLDP_FUNCTION,          lldp\src,      LLDP_FUNCTION,     1;
   TRACE_SUBSYS_NARE_UPPER,             nare\src,      NARE_UPPER,        1;
   TRACE_SUBSYS_NARE_SYSTEM,            nare\src,      NARE_SYSTEM,       1;
   TRACE_SUBSYS_NARE_PROGRAM,           nare\src,      NARE_PROGRAM,      1;
   TRACE_SUBSYS_NARE_LOWER,             nare\src,      NARE_LOWER,        1;
   TRACE_SUBSYS_NARE_FUNCTION,          nare\src,      NARE_FUNCTION,     1;
   TRACE_SUBSYS_OHA_UPPER,              oha\src,       OHA_UPPER,         1;
   TRACE_SUBSYS_OHA_SYSTEM,             oha\src,       OHA_SYSTEM,        1;
   TRACE_SUBSYS_OHA_PROGRAM,            oha\src,       OHA_PROGRAM,       1;
   TRACE_SUBSYS_OHA_LOWER,              oha\src,       OHA_LOWER,         1;
   TRACE_SUBSYS_OHA_FUNCTION,           oha\src,       OHA_FUNCTION,      1;
   TRACE_SUBSYS_PNTRC_SYSTEM,           pntrc\src,     PNTRC_SYSTEM,      1;
   TRACE_SUBSYS_PSI_HD,                 psi\src,       PSI_HD,            1;
   TRACE_SUBSYS_PSI_LD,                 psi\src,       PSI_LD,            1;
   TRACE_SUBSYS_PSI_SYSTEM,             psi\src,       PSI_SYSTEM,        1;
   TRACE_SUBSYS_SNMPX_UPPER,            snmpx\src,     SNMPX_UPPER,       1;
   TRACE_SUBSYS_SNMPX_SYSTEM,           snmpx\src,     SNMPX_SYSTEM,      1;
   TRACE_SUBSYS_SNMPX_PROGRAM,          snmpx\src,     SNMPX_PROGRAM,     1;
   TRACE_SUBSYS_SNMPX_LOWER,            snmpx\src,     SNMPX_LOWER,       1;
   TRACE_SUBSYS_SNMPX_MEMORY,           snmpx\src,     SNMPX_MEMORY,      1;
   TRACE_SUBSYS_SNMPX_PROTOCOL,         snmpx\src,     SNMPX_PROTOCOL,    1;
   TRACE_SUBSYS_SNMPX_FUNCTION,         snmpx\src,     SNMPX_FUNCTION,    1;
   TRACE_SUBSYS_SOCK_UPPER,             sock\src,      SOCK_UPPER,        1;
   TRACE_SUBSYS_SOCK_SYSTEM,            sock\src,      SOCK_SYSTEM,       1;
   TRACE_SUBSYS_SOCK_PROTOCOL,          sock\src,      SOCK_PROTOCOL,     1;
   TRACE_SUBSYS_SOCK_LOWER,             sock\src,      SOCK_LOWER,        1;
   TRACE_SUBSYS_TCIP_OBSD,              tcip,        TCIP_OBSD,         1;
   TRACE_SUBSYS_TCIP_OBSD,              tcip\../snmpx/src_obsd,  TCIP_OBSD,         1;
   TRACE_SUBSYS_TCIP_INICHE,            tcip,        TCIP_INICHE,       1;
   TRACE_SUBSYS_TCIP_MEM,               tcip,        TCIP_MEM,          1;
   TRACE_SUBSYS_TCIP_UPPER,             tcip,        TCIP_UPPER,        1;
   TRACE_SUBSYS_PND_SYSTEM,             pnd\src,       PND_SYSTEM,        1;
   TRACE_SUBSYS_PND_PNUC,               pnd\src,       PND_PNUC,          1;
   TRACE_SUBSYS_PND_IOBC,               pnd\src,       PND_IOBC,          1;
   TRACE_SUBSYS_PND_AGENT,              pnd\src,       PND_AGENT,         1;
   TRACE_SUBSYS_PND_PARAMS,             pnd\src,       PND_PARAMS,        1;
   TRACE_SUBSYS_PND_IODU,               pnd\src,       PND_IODU,          1;
   TRACE_SUBSYS_PND_PNTRC,              pnd\src,       PND_PNTRC,         1;
   TRACE_SUBSYS_PND_ISO,                pnd\src,       PND_ISO,           1;
   TRACE_SUBSYS_PND_OHA,                pnd\src,       PND_OHA,           1;
   TRACE_SUBSYS_PND_IOH,                pnd\src,       PND_IOH,           1;
   TRACE_SUBSYS_PND_IOC,                pnd\src,       PND_IOC,           1;
   TRACE_SUBSYS_PND_PD,                 pnd\src,       PND_PD,            1;

|@@@END-LTRC-Scanner-Params@@@|*/

#ifdef __cplusplus  /* If C++ - compiler: End of C linkage */
}
#endif
/*****************************************************************************/
/*  end of --AUTOGENERATED FILE--                                            */
/*****************************************************************************/

/*---------------------------------------------------------------------------*/
#endif/* of PNTRC_SUB_GEN_H */
