#ifndef EDDI_ERTEC_IMAGE_H      //reinclude-protection ----- */
#define EDDI_ERTEC_IMAGE_H

#ifdef __cplusplus              //If C++ - compiler: Use C linkage
extern "C"
{
#endif

/*****************************************************************************/
/*  Copyright (C) 2019 Siemens Aktiengesellschaft. All rights reserved.      */
/*****************************************************************************/
/*  This program is protected by German copyright law and international      */
/*  treaties. The use of this software including but not limited to its      */
/*  Source Code is subject to restrictions as agreed in the license          */
/*  agreement between you and Siemens.                                       */
/*  Copying or distribution is not allowed unless expressly permitted        */
/*  according to your license agreement with Siemens.                        */
/*****************************************************************************/
/*                                                                           */
/*  P r o j e c t         &P: PROFINET IO Runtime Software              :P&  */
/*                                                                           */
/*  P a c k a g e         &W: PROFINET IO Runtime Software              :W&  */
/*                                                                           */
/*  C o m p o n e n t     &C: EDDI (EthernetDeviceDriver for IRTE)      :C&  */
/*                                                                           */
/*  F i l e               &F: eddi_ertec_image.h                        :F&  */
/*                                                                           */
/*  V e r s i o n         &V: BC_PNRUN_P07.01.00.00_00.02.00.15         :V&  */
/*                                                                           */
/*  D a t e  (YYYY-MM-DD) &D: 2019-08-05                                :D&  */
/*                                                                           */
/*****************************************************************************/
/*                                                                           */
/*   D e s c r i p t i o n: File containing ERTEC400 image                   */
/*                                                                           */
/*   BUILD STRING : Ver. 1.0 [Build 1 (devellopment)]                        */
/*                                                                           */
/*   NOTE   : This file was automatically generated by a perl script.        */
/*          : (postbuild.pl: Rev : :0                                        */
/*          :                                                                */
/* ***************************************************************************/
/*                                                                           */
/*   H i s t o r y :                                                         */
/*   _______________________________________________________________________ */
/*                                                                           */
/*   Date                          Who   What                                */
/*   Thu Dec 22 17:18:12 2005      Frank Collin                              */
/*****************************************************************************/

typedef  struct FileLocater
{
    unsigned char name [60];
    unsigned long size;
    unsigned char * address;

} fileLoc_T;

extern fileLoc_T files[];

#ifdef __cplusplus //If C++ - compiler: End of C linkage
}
#endif

#endif //EDDI_ERTEC_IMAGE_H


/*****************************************************************************/
/*  end of file eddi_ertec_image.h                                           */
/*****************************************************************************/

