/*****************************************************************************/
/*  Copyright (C) 2xxx Siemens Aktiengesellschaft. All rights reserved.      */
/*****************************************************************************/
/*  This program is protected by German copyright law and international      */
/*  treaties. The use of this software including but not limited to its      */
/*  Source Code is subject to restrictions as agreed in the license          */
/*  agreement between you and Siemens.                                       */
/*  Copying or distribution is not allowed unless expressly permitted        */
/*  according to your license agreement with Siemens.                        */
/*****************************************************************************/
/*                                                                           */
/*  P r o j e c t         &P: PROFINET IO Runtime Software              :P&  */
/*                                                                           */
/*  P a c k a g e         &W: PROFINET IO Runtime Software              :W&  */
/*                                                                           */
/*  C o m p o n e n t     &C: PNTRC (PN Trace)                          :C&  */
/*                                                                           */
/*  F i l e               &F: pntrc_checksum.c                          :F&  */
/*                                                                           */
/*  V e r s i o n         &V: LSA_PNIO_Pxx.xx.xx.xx_xx.xx.xx.xx         :V&  */
/*                                                                           */
/*  D a t e  (YYYY-MM-DD) &D: xxxx-xx-xx                                :D&  */
/*                                                                           */
/*****************************************************************************/
/*                                                                           */
/*  D e s c r i p t i o n :                                                  */
/*                                                                           */
/*  Contains MD5sum of ltrcscanner output for correct binary trace decoding  */
/*                                                                           */
/*****************************************************************************/
/*                                                                           */
/* This file is automatically generated by ltrscanner Perl Script.           */
/* Do not modify manually as changes will be overwritten!                    */
/*                                                                           */
/*****************************************************************************/

#include "pntrc_inc.h"
#include "pntrc_sys.h"
#include "pntrc_cfg.h"

#ifdef PNTRC_CFG_CHECK_SCANNERINFO
void pntrc_get_md5sum_scannerinfo(LSA_UINT32* md5)
{
    md5[0] = 0xf058c961;
    md5[1] = 0x80cd7d0d;
    md5[2] = 0x6831d722;
    md5[3] = 0x4f8ba943;
}
#endif  /* PNTRC_CFG_CHECK_SCANNERINFO */
