/*****************************************************************************/
/*  Copyright (C) 2019 Siemens Aktiengesellschaft. All rights reserved.      */
/*****************************************************************************/
/*  This program is protected by German copyright law and international      */
/*  treaties. The use of this software including but not limited to its      */
/*  Source Code is subject to restrictions as agreed in the license          */
/*  agreement between you and Siemens.                                       */
/*  Copying or distribution is not allowed unless expressly permitted        */
/*  according to your license agreement with Siemens.                        */
/*****************************************************************************/
/*                                                                           */
/*  P r o j e c t         &P: PROFINET IO Runtime Software              :P&  */
/*                                                                           */
/*  P a c k a g e         &W: PROFINET IO Runtime Software              :W&  */
/*                                                                           */
/*  C o m p o n e n t     &C: HIF (Host Interface)                      :C&  */
/*                                                                           */
/*  F i l e               &F: hif_ser_nare.c                            :F&  */
/*                                                                           */
/*  V e r s i o n         &V: BC_PNRUN_P07.01.00.00_00.02.00.15         :V&  */
/*                                                                           */
/*  D a t e  (YYYY-MM-DD) &D: 2019-08-05                                :D&  */
/*                                                                           */
/*****************************************************************************/
/*                                                                           */
/*  D e s c r i p t i o n :                                                  */
/*                                                                           */
/*  Automatically generated with HIF Code Generator v2.4.1                   */
/*                                                                           */
/*                                                                           */
/*  !!!ATTENTION: Do not edit this file.                                     */
/*                Please use the HIF Code Generator to generate this file.   */
/*                                                                           */
/*  The hash value was automatically calculated by HIF Code Generator!       */
/*  HASH-VALUE: pC+0zdP9I12gZwGk7S9DHJNM9cxR4ibmpfr/V2dFX5s=                 */
/*****************************************************************************/

#if defined(TOOL_CHAIN_MICROSOFT) /* Microsoft Visual C++ */
#pragma component(browser, off, references)
#endif

#define LTRC_ACT_MODUL_ID   112
#define HIF_MODULE_ID       LTRC_ACT_MODUL_ID

#include "hif_int.h"      

/// @cond PREVENT_DOXYGEN
HIF_FILE_SYSTEM_EXTENSION(HIF_MODULE_ID)

/// @endcond
#if ( (HIF_CFG_COMPILE_SERIALIZATION == 1) && (HIF_CFG_USE_NARE == 1) )


//lint -save -e506
// Warning 506: Constant value Boolean; It is expected that these issues are optimized while compilation of source code.
//lint -save -e774
// Warning 774: If always evaluates to True; It is expected that these issues are optimized while compilation of source code.

/* Prototypes */


/* Helper Functions */

/**
* \brief Function serializes the RQB to the HIF shared memory according to the component ID and OP-code in the RQB. 
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] hShmPool          - pool handle for the transfer memory
* @param [in] pRqbSrc           - pointer to the RQB that is serialized
* @param [out] ppRqbDest        - pointer to the serialized RQB in the HIF transfer memory
* @param [out] pSerRqbLen       - total length of the serialized RQB in the transfer memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough memory available in the transfer memory
*/
LSA_UINT16  hif_nare_serialize_upper (
    HIF_SYS_HANDLE hSysDev,
    LSA_VOID*      pHifPipeHandle,
    LSA_INT        hShmPool,
    LSA_VOID*      pRqbSrc,
    LSA_VOID**     ppRqbDest,
    LSA_UINT32*    pSerRqbLen )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    LSA_UINT32 rqb_size = 0;
    LSA_OPCODE_TYPE opcode;
    NARE_RQB_TYPE* ptr_rqb_src = (NARE_RQB_TYPE*)pRqbSrc;
    LSA_VOID** ptr_ptr_rqb_dest = ppRqbDest;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src)); /*#5*/
    opcode=HIF_RQB_GET_OPCODE(ptr_rqb_src);

    if (opcode==NARE_OPC_OPEN_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_SYS_PATH_TYPE();        /* sys_path */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_SYS_PATH_HTSHM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.channel.sys_path);                /* sys_path */
    }
    else if (opcode==NARE_OPC_CLOSE_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
    }
    else if (opcode==NARE_OPC_IDENT)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(1);        /* StationNameLen */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "pStationName" pointer itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Ident.pStationName /* #8*/))
        {
            rqb_size+=HIF_SER_SIZEOF_BUF(ptr_rqb_src->args.Ident.StationNameLen);        /* size of: pStationName */
        }
        rqb_size+=HIF_SER_SIZEOF(2);        /* Tolerance */
        rqb_size+=HIF_SER_SIZEOF(4);        /* RequestID */
        rqb_size+=HIF_SER_SIZEOF(1);        /* Notify */
        rqb_size+=HIF_SER_SIZEOF(4);        /* NotifyID */
        rqb_size+=HIF_SER_SIZEOF(2);        /* AliasCnt */
        rqb_size+=HIF_SER_SIZEOF(4);        /* pStationNameAlias pointer */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        /* INFO: serialize the array size right after the pointer */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.AliasCnt);                /* AliasCnt */
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.StationNameLen);                /* StationNameLen */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.pStationName);        /* pointer info itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Ident.pStationName /*#11*/))
        {
            HIF_SER_COPY_HTSHM_BUFFER(&help_ptr,ptr_rqb_src->args.Ident.pStationName,ptr_rqb_src->args.Ident.StationNameLen, hSysDev);        /* pStationName */
        }
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.Tolerance);                /* Tolerance */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.RequestID);                /* RequestID */
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.Notify);                /* Notify */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.NotifyID);                /* NotifyID */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.pStationNameAlias);        /* pointer info itself */
    }
    else if (opcode==NARE_OPC_SET)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(1);        /* StationNameLen */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "pStationName" pointer itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Set.pStationName /* #8*/))
        {
            rqb_size+=HIF_SER_SIZEOF_BUF(ptr_rqb_src->args.Set.StationNameLen);        /* size of: pStationName */
        }
        rqb_size+=HIF_SER_SIZEOF(1);        /* Mode */
        rqb_size+=HIF_SER_SIZEOF(4);        /* RequestID */
        rqb_size+=HIF_SER_SIZEOF(1);        /* SetIPRemanent */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* IPAddr */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* SubMask */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* DefRouter */
        rqb_size+=(HIF_SER_SIZEOF(1) * 6);        /* MACAddr */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.StationNameLen);                /* StationNameLen */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.pStationName);        /* pointer info itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Set.pStationName /*#11*/))
        {
            HIF_SER_COPY_HTSHM_BUFFER(&help_ptr,ptr_rqb_src->args.Set.pStationName,ptr_rqb_src->args.Set.StationNameLen, hSysDev);        /* pStationName */
        }
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.Mode);                /* Mode */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.RequestID);                /* RequestID */
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.SetIPRemanent);                /* SetIPRemanent */
        for(i=0;i<4;i++)                        /* Set*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.IPAddr[i]);                /* IPAddr */
        }
        for(i=0;i<4;i++)                        /* Set*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.SubMask[i]);                /* SubMask */
        }
        for(i=0;i<4;i++)                        /* Set*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.DefRouter[i]);                /* DefRouter */
        }
        for(i=0;i<6;i++)                        /* Set*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Set.MACAddr[i]);                /* MACAddr */
        }
    }
    else if (opcode==NARE_OPC_CANCEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(4);        /* RequestID */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Cancel.RequestID);                /* RequestID */
    }
    else if (opcode==NARE_OPC_IDENT_NOTIFY)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
    }
    else if (opcode==NARE_OPC_TEST_IP)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* LocalIPAddr */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* IPAddr */
        rqb_size+=HIF_SER_SIZEOF(4);        /* RequestID */
        rqb_size+=HIF_SER_SIZEOF(1);        /* UseDelay */
        rqb_size+=HIF_SER_SIZEOF(1);        /* SniffMode */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        for(i=0;i<4;i++)                        /* TestIP*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.TestIP.LocalIPAddr[i]);                /* LocalIPAddr */
        }
        for(i=0;i<4;i++)                        /* TestIP*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.TestIP.IPAddr[i]);                /* IPAddr */
        }
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.TestIP.RequestID);                /* RequestID */
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.TestIP.UseDelay);                /* UseDelay */
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.TestIP.SniffMode);                /* SniffMode */
    }
    else if (opcode==NARE_OPC_RESOLVE_IP)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* LocalIPAddr */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* IPAddr */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        for(i=0;i<4;i++)                        /* ResolveIP*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ResolveIP.LocalIPAddr[i]);                /* LocalIPAddr */
        }
        for(i=0;i<4;i++)                        /* ResolveIP*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ResolveIP.IPAddr[i]);                /* IPAddr */
        }
    }
    else if (opcode==NARE_OPC_TIMER)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* TimerID */
        rqb_size+=HIF_SER_SIZEOF(4);        /* UserID */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Timer.TimerID);                /* TimerID */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Timer.UserID);                /* UserID */
    }
    else if (opcode==NARE_OPC_HELLO)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(4);        /* SendInterval */
        rqb_size+=HIF_SER_SIZEOF(4);        /* Delay */
        rqb_size+=HIF_SER_SIZEOF(4);        /* SendCnt */
        rqb_size+=HIF_SER_SIZEOF(4);        /* OptCnt */
        rqb_size+=HIF_SER_SIZEOF(4);        /* TLVLength */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "pTLV" pointer itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Hello.pTLV /* #8*/))
        {
            rqb_size+=HIF_SER_SIZEOF_BUF(ptr_rqb_src->args.Hello.TLVLength);        /* size of: pTLV */
        }
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Hello.SendInterval);                /* SendInterval */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Hello.Delay);                /* Delay */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Hello.SendCnt);                /* SendCnt */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Hello.OptCnt);                /* OptCnt */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Hello.TLVLength);                /* TLVLength */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Hello.pTLV);        /* pointer info itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Hello.pTLV /*#11*/))
        {
            HIF_SER_COPY_HTSHM_BUFFER(&help_ptr,ptr_rqb_src->args.Hello.pTLV,ptr_rqb_src->args.Hello.TLVLength, hSysDev);        /* pTLV */
        }
    }
    else if (opcode==NARE_OPC_HELLO_STOP)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(4);        /* RequestID */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.HelloStop.RequestID);                /* RequestID */
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_nare_serialize_upper(). RQB-Opcode:0x%x is not valid! pRQB(0x%08x)",opcode,ptr_rqb_src+4);
        HIF_FATAL(0);
    }

    *pSerRqbLen = rqb_size;

    HIF_ASSERT(HIF_IS_NOT_NULL(help_ptr)); /*#4*/

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_SERIALIZE(opcode, *ptr_ptr_rqb_dest, rqb_size, help_ptr, "hif_nare_serialize_upper");

    return HIF_OK;
}

/**
* \brief Function serializes the RQB to the HIF shared memory according to the component ID and OP-code in the RQB. 
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] hShmPool          - pool handle for the transfer memory
* @param [in] pRqbSrc           - pointer to the RQB that is serialized
* @param [out] ppRqbDest        - pointer to the serialized RQB in the HIF transfer memory
* @param [out] pSerRqbLen       - total length of the serialized RQB in the transfer memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough memory available in the transfer memory
*/
LSA_UINT16  hif_nare_serialize_lower (
    HIF_SYS_HANDLE hSysDev,
    LSA_VOID*      pHifPipeHandle,
    LSA_INT        hShmPool,
    LSA_VOID*      pRqbSrc,
    LSA_VOID**     ppRqbDest,
    LSA_UINT32*    pSerRqbLen )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    LSA_UINT32 rqb_size = 0;
    LSA_OPCODE_TYPE opcode;
    NARE_RQB_TYPE* ptr_rqb_src = (NARE_RQB_TYPE*)pRqbSrc;
    LSA_VOID** ptr_ptr_rqb_dest = ppRqbDest;
    LSA_UINT16 freeRes;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src)); /*#5*/
    opcode=HIF_RQB_GET_OPCODE(ptr_rqb_src);

    if (opcode==NARE_OPC_OPEN_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_CLOSE_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_IDENT)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(2);        /* AliasUsed */
        rqb_size+=(HIF_SER_SIZEOF(1) * 240);        /* IdentifiedStationName */
        rqb_size+=HIF_SER_SIZEOF(1);        /* IdentifiedStationNameLen */
        rqb_size+=HIF_SER_SIZEOF(2);        /* DeviceID */
        rqb_size+=HIF_SER_SIZEOF(2);        /* VendorID */
        rqb_size+=HIF_SER_SIZEOF(2);        /* InstanceID */
        rqb_size+=HIF_SER_SIZEOF(1);        /* InstanceIDValid */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* IPAddr */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* SubMask */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* DefRouter */
        rqb_size+=(HIF_SER_SIZEOF(1) * 6);        /* MACAddr */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.AliasUsed);                /* AliasUsed */
        for(i=0;i<240;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.IdentifiedStationName[i]);                /* IdentifiedStationName */
        }
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.IdentifiedStationNameLen);                /* IdentifiedStationNameLen */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.DeviceID);                /* DeviceID */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.VendorID);                /* VendorID */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.InstanceID);                /* InstanceID */
        HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.InstanceIDValid);                /* InstanceIDValid */
        for(i=0;i<4;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.IPAddr[i]);                /* IPAddr */
        }
        for(i=0;i<4;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.SubMask[i]);                /* SubMask */
        }
        for(i=0;i<4;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.DefRouter[i]);                /* DefRouter */
        }
        for(i=0;i<6;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.Ident.MACAddr[i]);                /* MACAddr */
        }

        /* Delete lower RQB after lower serialization */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Ident.pStationName)) /*#13*/
        {
            freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
            HIF_FREE_LOCAL_MEMORY(&freeRes, ptr_rqb_src->args.Ident.pStationName, LSA_COMP_ID_NARE, HIF_MEM_TYPE_BUFFER, hSysDev);
            if (freeRes != LSA_RET_OK)
            {
                return HIF_ERR_RESOURCE;
            }
        }
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Ident.pStationNameAlias)) /*#15*/
        {
            freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
            HIF_FREE_LOCAL_MEMORY(&freeRes, ptr_rqb_src->args.Ident.pStationNameAlias, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
            if (freeRes != LSA_RET_OK)
            {
                return HIF_ERR_RESOURCE;
            }
        }
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_SET)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Set.pStationName)) /*#13*/
        {
            freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
            HIF_FREE_LOCAL_MEMORY(&freeRes, ptr_rqb_src->args.Set.pStationName, LSA_COMP_ID_NARE, HIF_MEM_TYPE_BUFFER, hSysDev);
            if (freeRes != LSA_RET_OK)
            {
                return HIF_ERR_RESOURCE;
            }
        }
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_CANCEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_IDENT_NOTIFY)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(4);        /* NotifyID */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* IPAddr */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* SubMask */
        rqb_size+=(HIF_SER_SIZEOF(1) * 4);        /* DefRouter */
        rqb_size+=(HIF_SER_SIZEOF(1) * 6);        /* MACAddr */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.IdentNotify.NotifyID);                /* NotifyID */
        for(i=0;i<4;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.IdentNotify.Ident.IPAddr[i]);                /* IPAddr */
        }
        for(i=0;i<4;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.IdentNotify.Ident.SubMask[i]);                /* SubMask */
        }
        for(i=0;i<4;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.IdentNotify.Ident.DefRouter[i]);                /* DefRouter */
        }
        for(i=0;i<6;i++)                        /* Ident*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.IdentNotify.Ident.MACAddr[i]);                /* MACAddr */
        }

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_TEST_IP)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=(HIF_SER_SIZEOF(1) * 6);        /* MACAddr */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        for(i=0;i<6;i++)                        /* TestIP*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.TestIP.MACAddr[i]);                /* MACAddr */
        }

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_RESOLVE_IP)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=(HIF_SER_SIZEOF(1) * 6);        /* MACAddr */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        for(i=0;i<6;i++)                        /* ResolveIP*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ResolveIP.MACAddr[i]);                /* MACAddr */
        }

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_TIMER)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_HELLO)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.Hello.pTLV)) /*#13*/
        {
            freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
            HIF_FREE_LOCAL_MEMORY(&freeRes, ptr_rqb_src->args.Hello.pTLV, LSA_COMP_ID_NARE, HIF_MEM_TYPE_BUFFER, hSysDev);
            if (freeRes != LSA_RET_OK)
            {
                return HIF_ERR_RESOURCE;
            }
        }
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==NARE_OPC_HELLO_STOP)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_nare_serialize_lower(). RQB-Opcode:0x%x is not valid! pRQB(0x%08x)",opcode,ptr_rqb_src+4);
        HIF_FATAL(0);
    }

    *pSerRqbLen = rqb_size;

    HIF_ASSERT(HIF_IS_NOT_NULL(help_ptr)); /*#4*/

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_SERIALIZE(opcode, *ptr_ptr_rqb_dest, rqb_size, help_ptr, "hif_nare_serialize_lower");

    return HIF_OK;
}

/**
* \brief De-serializes the RQB from the HIF shared memory into the hosts local memory - according to the component ID and OP-code in the RQB.
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] pRqbSrc           - pointer to the serialized RQB in the transfer memory
* @param [out] ppRqbDest        - pointer to the RQB deserialized in the hosts local memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough local memory
*/
LSA_UINT16      hif_nare_deserialize_upper (
        HIF_SYS_HANDLE hSysDev,
        LSA_VOID* pHifPipeHandle,
        LSA_VOID* pRqbSrc,
        LSA_VOID** ppRqbDest )
{
    LSA_UINT8* help_ptr;
    NARE_RQB_TYPE* new_rqb;
    LSA_OPCODE_TYPE opcode;
    LSA_VOID* ptr_rqb_src = (LSA_VOID*)pRqbSrc;
    NARE_RQB_TYPE** ptr_ptr_rqb_dest = (NARE_RQB_TYPE**)ppRqbDest;
    LSA_RESPONSE_TYPE response = 0;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_ptr_rqb_dest)); /*#17*/
    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src));

    HIF_DESER_GET_OPCODE(ptr_rqb_src, opcode);

    help_ptr = (LSA_UINT8*)ptr_rqb_src + HIF_SER_SIZEOF(4);  /* start deserialization after the original upper RQB pointer */

    new_rqb = (NARE_RQB_TYPE*)hif_get_rqb_id(ptr_rqb_src); /* get orig. upper RQB */
    HIF_PROGRAM_TRACE_03(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_upper() opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,ptr_rqb_src,new_rqb+4);

    if (opcode==NARE_OPC_OPEN_CHANNEL)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==NARE_OPC_CLOSE_CHANNEL)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==NARE_OPC_IDENT)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.Ident.AliasUsed,(LSA_UINT32**)&help_ptr);        /* AliasUsed */
        for(i=0;i<240;i++)                        /* IdentifiedStationName*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.IdentifiedStationName[i],(LSA_UINT32**)&help_ptr);        /* IdentifiedStationName */
        }
        HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.IdentifiedStationNameLen,(LSA_UINT32**)&help_ptr);        /* IdentifiedStationNameLen */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.Ident.DeviceID,(LSA_UINT32**)&help_ptr);        /* DeviceID */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.Ident.VendorID,(LSA_UINT32**)&help_ptr);        /* VendorID */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.Ident.InstanceID,(LSA_UINT32**)&help_ptr);        /* InstanceID */
        HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.InstanceIDValid,(LSA_UINT32**)&help_ptr);        /* InstanceIDValid */
        for(i=0;i<4;i++)                        /* IPAddr*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.IPAddr[i],(LSA_UINT32**)&help_ptr);        /* IPAddr */
        }
        for(i=0;i<4;i++)                        /* SubMask*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.SubMask[i],(LSA_UINT32**)&help_ptr);        /* SubMask */
        }
        for(i=0;i<4;i++)                        /* DefRouter*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.DefRouter[i],(LSA_UINT32**)&help_ptr);        /* DefRouter */
        }
        for(i=0;i<6;i++)                        /* MACAddr*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.MACAddr[i],(LSA_UINT32**)&help_ptr);        /* MACAddr */
        }
    }
    else if (opcode==NARE_OPC_SET)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==NARE_OPC_CANCEL)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==NARE_OPC_IDENT_NOTIFY)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.IdentNotify.NotifyID,(LSA_UINT32**)&help_ptr);        /* NotifyID */
        for(i=0;i<4;i++)                        /* IPAddr*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.IdentNotify.Ident.IPAddr[i],(LSA_UINT32**)&help_ptr);        /* IPAddr */
        }
        for(i=0;i<4;i++)                        /* SubMask*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.IdentNotify.Ident.SubMask[i],(LSA_UINT32**)&help_ptr);        /* SubMask */
        }
        for(i=0;i<4;i++)                        /* DefRouter*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.IdentNotify.Ident.DefRouter[i],(LSA_UINT32**)&help_ptr);        /* DefRouter */
        }
        for(i=0;i<6;i++)                        /* MACAddr*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.IdentNotify.Ident.MACAddr[i],(LSA_UINT32**)&help_ptr);        /* MACAddr */
        }
    }
    else if (opcode==NARE_OPC_TEST_IP)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        for(i=0;i<6;i++)                        /* MACAddr*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.TestIP.MACAddr[i],(LSA_UINT32**)&help_ptr);        /* MACAddr */
        }
    }
    else if (opcode==NARE_OPC_RESOLVE_IP)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        for(i=0;i<6;i++)                        /* MACAddr*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.ResolveIP.MACAddr[i],(LSA_UINT32**)&help_ptr);        /* MACAddr */
        }
    }
    else if (opcode==NARE_OPC_TIMER)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==NARE_OPC_HELLO)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==NARE_OPC_HELLO_STOP)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_nare_deserialize_upper(). RQB-Opcode:0x%x is not valid! shm_addr(0x%08x)", opcode, ptr_rqb_src);
        HIF_FATAL(0);
    }
    *ptr_ptr_rqb_dest = new_rqb;

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_DESERIALIZE(ptr_rqb_src, opcode, help_ptr, "hif_nare_deserialize_upper");

    return HIF_OK;
}

/**
* \brief De-serializes the RQB from the HIF shared memory into the hosts local memory - according to the component ID and OP-code in the RQB.
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] pRqbSrc           - pointer to the serialized RQB in the transfer memory
* @param [out] ppRqbDest        - pointer to the RQB deserialized in the hosts local memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough local memory
*/
LSA_UINT16      hif_nare_deserialize_lower (
        HIF_SYS_HANDLE hSysDev,
        LSA_VOID* pHifPipeHandle,
        LSA_VOID* pRqbSrc,
        LSA_VOID** ppRqbDest )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    NARE_RQB_TYPE* new_rqb  = LSA_NULL;
    LSA_OPCODE_TYPE opcode;
    LSA_VOID* ptr_rqb_src = (LSA_VOID*)pRqbSrc;
    NARE_RQB_TYPE** ptr_ptr_rqb_dest = (NARE_RQB_TYPE**)ppRqbDest;
    LSA_UINT32 rqb_size = 0;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_ptr_rqb_dest)); /*#17*/
    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src));

    HIF_DESER_GET_OPCODE(ptr_rqb_src, opcode);

    if (opcode==NARE_OPC_OPEN_CHANNEL)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_SYS_PATH_SHMTH(&new_rqb->args.channel.sys_path,(LSA_UINT32**)&help_ptr);            /* sys_path */
        }
    }
    else if (opcode==NARE_OPC_CLOSE_CHANNEL)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
        }
    }
    else if (opcode==NARE_OPC_IDENT)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            /* INFO: deserialize the array size from right after the pointer */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.Ident.AliasCnt,(LSA_UINT32**)&help_ptr);            /* AliasCnt */
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.StationNameLen,(LSA_UINT32**)&help_ptr);            /* StationNameLen */
            if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.Ident.StationNameLen > 0 ) /*#22d*/
            {
                help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer pointer */
                HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb->args.Ident.pStationName,new_rqb->args.Ident.StationNameLen, LSA_COMP_ID_NARE, HIF_MEM_TYPE_BUFFER );
                HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() allocate buffer buffer_size(%d) opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",new_rqb->args.Ident.StationNameLen,opcode,help_ptr,new_rqb+4);
                if (HIF_IS_NOT_NULL(new_rqb->args.Ident.pStationName)) /*#23*/
                {
                    HIF_SER_COPY_SHMTH_BUF(new_rqb->args.Ident.pStationName,&help_ptr,new_rqb->args.Ident.StationNameLen);            /* pStationName */
                }
                else
                {
                    return HIF_ERR_RESOURCE;
                }
            }
            else
            {
                new_rqb->args.Ident.pStationName = LSA_NULL; /* set data buffer pointer to NULL */
                help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
            }
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.Ident.Tolerance,(LSA_UINT32**)&help_ptr);            /* Tolerance */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Ident.RequestID,(LSA_UINT32**)&help_ptr);            /* RequestID */
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Ident.Notify,(LSA_UINT32**)&help_ptr);            /* Notify */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Ident.NotifyID,(LSA_UINT32**)&help_ptr);            /* NotifyID */
            if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr))            /* => pointer "pStationNameAlias" on shared-mem */ /*#20*/
            {
                /*lint --e(666) */
                HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&(new_rqb->args.Ident.pStationNameAlias), new_rqb->args.Ident.AliasCnt * sizeof(*new_rqb->args.Ident.pStationNameAlias), LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB );
                if (HIF_IS_NULL(new_rqb->args.Ident.pStationNameAlias))
                {
                    return HIF_ERR_RESOURCE;
                }
                help_ptr+=HIF_SER_SIZEOF(4);
            }
            else
            {
                help_ptr+=4;          /* skip buffer pointer */
                new_rqb->args.Ident.pStationNameAlias = LSA_NULL; /* set dynamic array pointer to NULL */
            }
        }
    }
    else if (opcode==NARE_OPC_SET)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Set.StationNameLen,(LSA_UINT32**)&help_ptr);            /* StationNameLen */
            if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.Set.StationNameLen > 0 ) /*#22d*/
            {
                help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer pointer */
                HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb->args.Set.pStationName,new_rqb->args.Set.StationNameLen, LSA_COMP_ID_NARE, HIF_MEM_TYPE_BUFFER );
                HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() allocate buffer buffer_size(%d) opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",new_rqb->args.Set.StationNameLen,opcode,help_ptr,new_rqb+4);
                if (HIF_IS_NOT_NULL(new_rqb->args.Set.pStationName)) /*#23*/
                {
                    HIF_SER_COPY_SHMTH_BUF(new_rqb->args.Set.pStationName,&help_ptr,new_rqb->args.Set.StationNameLen);            /* pStationName */
                }
                else
                {
                    return HIF_ERR_RESOURCE;
                }
            }
            else
            {
                new_rqb->args.Set.pStationName = LSA_NULL; /* set data buffer pointer to NULL */
                help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
            }
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Set.Mode,(LSA_UINT32**)&help_ptr);            /* Mode */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Set.RequestID,(LSA_UINT32**)&help_ptr);            /* RequestID */
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.Set.SetIPRemanent,(LSA_UINT32**)&help_ptr);            /* SetIPRemanent */
            for(i=0;i<4;i++)                                    /* IPAddr*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.Set.IPAddr[i],(LSA_UINT32**)&help_ptr);            /* IPAddr */
            }
            for(i=0;i<4;i++)                                    /* SubMask*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.Set.SubMask[i],(LSA_UINT32**)&help_ptr);            /* SubMask */
            }
            for(i=0;i<4;i++)                                    /* DefRouter*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.Set.DefRouter[i],(LSA_UINT32**)&help_ptr);            /* DefRouter */
            }
            for(i=0;i<6;i++)                                    /* MACAddr*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.Set.MACAddr[i],(LSA_UINT32**)&help_ptr);            /* MACAddr */
            }
        }
    }
    else if (opcode==NARE_OPC_CANCEL)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Cancel.RequestID,(LSA_UINT32**)&help_ptr);            /* RequestID */
        }
    }
    else if (opcode==NARE_OPC_IDENT_NOTIFY)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
        }
    }
    else if (opcode==NARE_OPC_TEST_IP)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            for(i=0;i<4;i++)                                    /* LocalIPAddr*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.TestIP.LocalIPAddr[i],(LSA_UINT32**)&help_ptr);            /* LocalIPAddr */
            }
            for(i=0;i<4;i++)                                    /* IPAddr*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.TestIP.IPAddr[i],(LSA_UINT32**)&help_ptr);            /* IPAddr */
            }
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.TestIP.RequestID,(LSA_UINT32**)&help_ptr);            /* RequestID */
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.TestIP.UseDelay,(LSA_UINT32**)&help_ptr);            /* UseDelay */
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.TestIP.SniffMode,(LSA_UINT32**)&help_ptr);            /* SniffMode */
        }
    }
    else if (opcode==NARE_OPC_RESOLVE_IP)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            for(i=0;i<4;i++)                                    /* LocalIPAddr*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.ResolveIP.LocalIPAddr[i],(LSA_UINT32**)&help_ptr);            /* LocalIPAddr */
            }
            for(i=0;i<4;i++)                                    /* IPAddr*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.ResolveIP.IPAddr[i],(LSA_UINT32**)&help_ptr);            /* IPAddr */
            }
        }
    }
    else if (opcode==NARE_OPC_TIMER)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.Timer.TimerID,(LSA_UINT32**)&help_ptr);            /* TimerID */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Timer.UserID,(LSA_UINT32**)&help_ptr);            /* UserID */
        }
    }
    else if (opcode==NARE_OPC_HELLO)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Hello.SendInterval,(LSA_UINT32**)&help_ptr);            /* SendInterval */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Hello.Delay,(LSA_UINT32**)&help_ptr);            /* Delay */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Hello.SendCnt,(LSA_UINT32**)&help_ptr);            /* SendCnt */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Hello.OptCnt,(LSA_UINT32**)&help_ptr);            /* OptCnt */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.Hello.TLVLength,(LSA_UINT32**)&help_ptr);            /* TLVLength */
            if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.Hello.TLVLength > 0 ) /*#22d*/
            {
                help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer pointer */
                HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb->args.Hello.pTLV,new_rqb->args.Hello.TLVLength, LSA_COMP_ID_NARE, HIF_MEM_TYPE_BUFFER );
                HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() allocate buffer buffer_size(%d) opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",new_rqb->args.Hello.TLVLength,opcode,help_ptr,new_rqb+4);
                if (HIF_IS_NOT_NULL(new_rqb->args.Hello.pTLV)) /*#23*/
                {
                    HIF_SER_COPY_SHMTH_BUF(new_rqb->args.Hello.pTLV,&help_ptr,new_rqb->args.Hello.TLVLength);            /* pTLV */
                }
                else
                {
                    return HIF_ERR_RESOURCE;
                }
            }
            else
            {
                new_rqb->args.Hello.pTLV = LSA_NULL; /* set data buffer pointer to NULL */
                help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
            }
        }
    }
    else if (opcode==NARE_OPC_HELLO_STOP)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(NARE_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_NARE, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_nare_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(NARE_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.HelloStop.RequestID,(LSA_UINT32**)&help_ptr);            /* RequestID */
        }
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_nare_deserialize_lower(). RQB-Opcode:0x%x is not valid! shm_addr(0x%08x)", opcode, ptr_rqb_src);
        HIF_FATAL(0);
    }
    HIF_RQB_SET_COMP_ID(new_rqb, LSA_COMP_ID_NARE);            /* set comp id */
    *ptr_ptr_rqb_dest = new_rqb;

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_DESERIALIZE(ptr_rqb_src, opcode, help_ptr, "hif_nare_deserialize_lower");

    return HIF_OK;
}


//lint -restore -e506
//lint -restore -e774

#endif /* of HIF_CFG_USE_NARE */
#if defined(TOOL_CHAIN_MICROSOFT) /* Microsoft Visual C++ */
#pragma component(browser, on, references)
#endif
/*****************************************************************************/
/* End of File                                                               */
/*****************************************************************************/
