/*****************************************************************************/
/*  Copyright (C) 2019 Siemens Aktiengesellschaft. All rights reserved.      */
/*****************************************************************************/
/*  This program is protected by German copyright law and international      */
/*  treaties. The use of this software including but not limited to its      */
/*  Source Code is subject to restrictions as agreed in the license          */
/*  agreement between you and Siemens.                                       */
/*  Copying or distribution is not allowed unless expressly permitted        */
/*  according to your license agreement with Siemens.                        */
/*****************************************************************************/
/*                                                                           */
/*  P r o j e c t         &P: PROFINET IO Runtime Software              :P&  */
/*                                                                           */
/*  P a c k a g e         &W: PROFINET IO Runtime Software              :W&  */
/*                                                                           */
/*  C o m p o n e n t     &C: HIF (Host Interface)                      :C&  */
/*                                                                           */
/*  F i l e               &F: hif_ser_mrp.c                             :F&  */
/*                                                                           */
/*  V e r s i o n         &V: BC_PNRUN_P07.01.00.00_00.02.00.15         :V&  */
/*                                                                           */
/*  D a t e  (YYYY-MM-DD) &D: 2019-08-05                                :D&  */
/*                                                                           */
/*****************************************************************************/
/*                                                                           */
/*  D e s c r i p t i o n :                                                  */
/*                                                                           */
/*  Automatically generated with HIF Code Generator v2.4.1                   */
/*                                                                           */
/*                                                                           */
/*  !!!ATTENTION: Do not edit this file.                                     */
/*                Please use the HIF Code Generator to generate this file.   */
/*                                                                           */
/*  The hash value was automatically calculated by HIF Code Generator!       */
/*  HASH-VALUE: R85PuOhqSl8l37jWcxm4FCndFcG4M1RmngyR/0MRrBQ=                 */
/*****************************************************************************/

#if defined(TOOL_CHAIN_MICROSOFT) /* Microsoft Visual C++ */
#pragma component(browser, off, references)
#endif

#define LTRC_ACT_MODUL_ID   111
#define HIF_MODULE_ID       LTRC_ACT_MODUL_ID

#include "hif_int.h"      

/// @cond PREVENT_DOXYGEN
HIF_FILE_SYSTEM_EXTENSION(HIF_MODULE_ID)

/// @endcond
#if ( (HIF_CFG_COMPILE_SERIALIZATION == 1) && (HIF_CFG_USE_MRP == 1) )


//lint -save -e506
// Warning 506: Constant value Boolean; It is expected that these issues are optimized while compilation of source code.
//lint -save -e774
// Warning 774: If always evaluates to True; It is expected that these issues are optimized while compilation of source code.

/* Prototypes */


/* Helper Functions */

/**
* \brief Function serializes the RQB to the HIF shared memory according to the component ID and OP-code in the RQB. 
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] hShmPool          - pool handle for the transfer memory
* @param [in] pRqbSrc           - pointer to the RQB that is serialized
* @param [out] ppRqbDest        - pointer to the serialized RQB in the HIF transfer memory
* @param [out] pSerRqbLen       - total length of the serialized RQB in the transfer memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough memory available in the transfer memory
*/
LSA_UINT16  hif_mrp_serialize_upper (
    HIF_SYS_HANDLE hSysDev,
    LSA_VOID*      pHifPipeHandle,
    LSA_INT        hShmPool,
    LSA_VOID*      pRqbSrc,
    LSA_VOID**     ppRqbDest,
    LSA_UINT32*    pSerRqbLen )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    LSA_UINT32 rqb_size = 0;
    LSA_OPCODE_TYPE opcode;
    MRP_RQB_TYPE* ptr_rqb_src = (MRP_RQB_TYPE*)pRqbSrc;
    LSA_VOID** ptr_ptr_rqb_dest = ppRqbDest;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src)); /*#5*/
    opcode=HIF_RQB_GET_OPCODE(ptr_rqb_src);

    if (opcode==MRP_OPC_OPEN_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_SYS_PATH_TYPE();        /* sys_path */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_SYS_PATH_HTSHM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.channel.open.sys_path);                /* sys_path */
    }
    else if (opcode==MRP_OPC_CLOSE_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
    }
    else if  ((opcode==MRP_OPC_PRM_READ)
            ||(opcode==MRP_OPC_PRM_READ_ADMIN_DATA))
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* slot_number */
        rqb_size+=HIF_SER_SIZEOF(2);        /* subslot_number */
        rqb_size+=HIF_SER_SIZEOF(2);        /* edd_port_id */
        rqb_size+=HIF_SER_SIZEOF(4);        /* record_index */
        rqb_size+=HIF_SER_SIZEOF(4);        /* record_data_length */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.prm_read.slot_number);                /* slot_number */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.prm_read.subslot_number);                /* subslot_number */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.prm_read.edd_port_id);                /* edd_port_id */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.prm_read.record_index);                /* record_index */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.prm_read.record_data_length);                /* record_data_length */
    }
    else if (opcode==MRP_OPC_GET_STATUS)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* mrpInstance */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainNameLength */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "pDomainName" pointer itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.ctrl.get_status.pDomainName /* #8*/))
        {
            rqb_size+=HIF_SER_SIZEOF_BUF(ptr_rqb_src->args.ctrl.get_status.domainNameLength);        /* size of: pDomainName */
        }
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.mrpInstance);                /* mrpInstance */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainNameLength);                /* domainNameLength */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.pDomainName);        /* pointer info itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.ctrl.get_status.pDomainName /*#11*/))
        {
            HIF_SER_COPY_HTSHM_BUFFER(&help_ptr,ptr_rqb_src->args.ctrl.get_status.pDomainName,ptr_rqb_src->args.ctrl.get_status.domainNameLength, hSysDev);        /* pDomainName */
        }
    }
    else if (opcode==MRP_OPC_SET_STATUS)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* mrpInstance */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainResetRoundTripDelays */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.set_status.mrpInstance);                /* mrpInstance */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.set_status.domainResetRoundTripDelays);                /* domainResetRoundTripDelays */
    }
    else if (opcode==MRP_OPC_STATE_INDICATION)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* mrpInstance */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.usrStateInd.mrpInstance);                /* mrpInstance */
    }
    else if (opcode==MRP_OPC_RED_STATE_INDICATION)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* mrpInstance */
        rqb_size+=HIF_SER_SIZEOF(2);        /* initState */
        rqb_size+=HIF_SER_SIZEOF(2);        /* startState */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rport1 */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rport2 */
        rqb_size+=(HIF_SER_SIZEOF(2) * 4);        /* stdbyPorts */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.mrpInstance);                /* mrpInstance */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.initState);                /* initState */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.startState);                /* startState */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.rport1);                /* rport1 */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.rport2);                /* rport2 */
        for(i=0;i<4;i++)                        /* redStateInd*/
        {
            HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.stdbyPorts[i]);                /* stdbyPorts */
        }
    }
    else if (opcode==MRP_OPC_RINGSTATE_INDICATION)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* mrpInstance */
        rqb_size+=(HIF_SER_SIZEOF(1) * 16);        /* domainUUID */
        rqb_size+=HIF_SER_SIZEOF(4);        /* topoCtrlMode */
        rqb_size+=HIF_SER_SIZEOF(4);        /* mrpStatus */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rPort1 */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rPort2 */
        rqb_size+=HIF_SER_SIZEOF(4);        /* adminRole */
        rqb_size+=HIF_SER_SIZEOF(4);        /* operRole */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainBlocked */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainVlanId */
        rqb_size+=HIF_SER_SIZEOF(2);        /* domainManagerPrio */
        rqb_size+=HIF_SER_SIZEOF(2);        /* domainMrmReactOnLinkChange */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.mrpInstance);                /* mrpInstance */
        for(i=0;i<16;i++)                        /* ohaStateInd*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainUUID[i]);                /* domainUUID */
        }
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.topoCtrlMode,MRP_USR_ENUM_TOPO_CTRL);                /* topoCtrlMode */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.mrpStatus);                /* mrpStatus */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.rPort1);                /* rPort1 */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.rPort2);                /* rPort2 */
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.adminRole,MRP_MIB_ENUM_DOMAIN_ROLE);                /* adminRole */
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.operRole,MRP_MIB_ENUM_DOMAIN_ROLE);                /* operRole */
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainBlocked,MRP_MIB_ENUM_DOMAIN_BLOCKED);                /* domainBlocked */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainVlanId);                /* domainVlanId */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainManagerPrio);                /* domainManagerPrio */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainMrmReactOnLinkChange);                /* domainMrmReactOnLinkChange */
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_mrp_serialize_upper(). RQB-Opcode:0x%x is not valid! pRQB(0x%08x)",opcode,ptr_rqb_src+4);
        HIF_FATAL(0);
    }

    *pSerRqbLen = rqb_size;

    HIF_ASSERT(HIF_IS_NOT_NULL(help_ptr)); /*#4*/

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_SERIALIZE(opcode, *ptr_ptr_rqb_dest, rqb_size, help_ptr, "hif_mrp_serialize_upper");

    return HIF_OK;
}

/**
* \brief Function serializes the RQB to the HIF shared memory according to the component ID and OP-code in the RQB. 
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] hShmPool          - pool handle for the transfer memory
* @param [in] pRqbSrc           - pointer to the RQB that is serialized
* @param [out] ppRqbDest        - pointer to the serialized RQB in the HIF transfer memory
* @param [out] pSerRqbLen       - total length of the serialized RQB in the transfer memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough memory available in the transfer memory
*/
LSA_UINT16  hif_mrp_serialize_lower (
    HIF_SYS_HANDLE hSysDev,
    LSA_VOID*      pHifPipeHandle,
    LSA_INT        hShmPool,
    LSA_VOID*      pRqbSrc,
    LSA_VOID**     ppRqbDest,
    LSA_UINT32*    pSerRqbLen )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    LSA_UINT32 rqb_size = 0;
    LSA_OPCODE_TYPE opcode;
    MRP_RQB_TYPE* ptr_rqb_src = (MRP_RQB_TYPE*)pRqbSrc;
    LSA_VOID** ptr_ptr_rqb_dest = ppRqbDest;
    LSA_UINT16 freeRes;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src)); /*#5*/
    opcode=HIF_RQB_GET_OPCODE(ptr_rqb_src);

    if (opcode==MRP_OPC_OPEN_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==MRP_OPC_CLOSE_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if  ((opcode==MRP_OPC_PRM_READ)
            ||(opcode==MRP_OPC_PRM_READ_ADMIN_DATA))
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(4);        /* record_data_length */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "record_data" pointer itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.ctrl.prm_read.record_data /* #8*/))
        {
            rqb_size+=HIF_SER_SIZEOF_BUF(ptr_rqb_src->args.ctrl.prm_read.record_data_length);        /* size of: record_data */
        }
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.prm_read.record_data_length);                /* record_data_length */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.prm_read.record_data);        /* pointer info itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.ctrl.prm_read.record_data /*#11*/))
        {
            HIF_SER_COPY_HTSHM_BUFFER(&help_ptr,ptr_rqb_src->args.ctrl.prm_read.record_data,ptr_rqb_src->args.ctrl.prm_read.record_data_length, hSysDev);        /* record_data */
        }

        /* Delete lower RQB after lower serialization */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.ctrl.prm_read.record_data)) /*#13*/
        {
            freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
            HIF_FREE_LOCAL_MEMORY(&freeRes, ptr_rqb_src->args.ctrl.prm_read.record_data, LSA_COMP_ID_MRP, HIF_MEM_TYPE_BUFFER, hSysDev);
            if (freeRes != LSA_RET_OK)
            {
                return HIF_ERR_RESOURCE;
            }
        }
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==MRP_OPC_GET_STATUS)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainNameLength */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "pDomainName" pointer itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.ctrl.get_status.pDomainName /* #8*/))
        {
            rqb_size+=HIF_SER_SIZEOF_BUF(ptr_rqb_src->args.ctrl.get_status.domainNameLength);        /* size of: pDomainName */
        }
        rqb_size+=HIF_SER_SIZEOF(4);        /* operRole */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rPort1 */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rPort2 */
        rqb_size+=HIF_SER_SIZEOF(4);        /* rPort1State */
        rqb_size+=HIF_SER_SIZEOF(4);        /* rPort2State */
        rqb_size+=HIF_SER_SIZEOF(2);        /* domainState */
        rqb_size+=HIF_SER_SIZEOF(2);        /* domainError */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainRingOpenCount */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainLastRingOpenChange */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainRoundTripDelayMax */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainRoundTripDelayMin */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainResetRoundTripDelays */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainNameLength);                /* domainNameLength */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.pDomainName);        /* pointer info itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.ctrl.get_status.pDomainName /*#11*/))
        {
            HIF_SER_COPY_HTSHM_BUFFER(&help_ptr,ptr_rqb_src->args.ctrl.get_status.pDomainName,ptr_rqb_src->args.ctrl.get_status.domainNameLength, hSysDev);        /* pDomainName */
        }
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.operRole,MRP_MIB_ENUM_DOMAIN_ROLE);                /* operRole */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.rPort1);                /* rPort1 */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.rPort2);                /* rPort2 */
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.rPort1State,MRP_MIB_ENUM_RPORT_STATE);                /* rPort1State */
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.rPort2State,MRP_MIB_ENUM_RPORT_STATE);                /* rPort2State */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainState);                /* domainState */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainError);                /* domainError */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainRingOpenCount);                /* domainRingOpenCount */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainLastRingOpenChange);                /* domainLastRingOpenChange */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainRoundTripDelayMax);                /* domainRoundTripDelayMax */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainRoundTripDelayMin);                /* domainRoundTripDelayMin */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.ctrl.get_status.domainResetRoundTripDelays);                /* domainResetRoundTripDelays */

        /* Delete lower RQB after lower serialization */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.ctrl.get_status.pDomainName)) /*#13*/
        {
            freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
            HIF_FREE_LOCAL_MEMORY(&freeRes, ptr_rqb_src->args.ctrl.get_status.pDomainName, LSA_COMP_ID_MRP, HIF_MEM_TYPE_BUFFER, hSysDev);
            if (freeRes != LSA_RET_OK)
            {
                return HIF_ERR_RESOURCE;
            }
        }
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==MRP_OPC_SET_STATUS)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==MRP_OPC_STATE_INDICATION)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(4);        /* mrpDiag */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.usrStateInd.mrpDiag);                /* mrpDiag */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==MRP_OPC_RED_STATE_INDICATION)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(2);        /* initState */
        rqb_size+=HIF_SER_SIZEOF(2);        /* startState */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rport1 */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rport2 */
        rqb_size+=(HIF_SER_SIZEOF(2) * 4);        /* stdbyPorts */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.initState);                /* initState */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.startState);                /* startState */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.rport1);                /* rport1 */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.rport2);                /* rport2 */
        for(i=0;i<4;i++)                        /* redStateInd*/
        {
            HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.redStateInd.stdbyPorts[i]);                /* stdbyPorts */
        }

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==MRP_OPC_RINGSTATE_INDICATION)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=(HIF_SER_SIZEOF(1) * 16);        /* domainUUID */
        rqb_size+=HIF_SER_SIZEOF(4);        /* topoCtrlMode */
        rqb_size+=HIF_SER_SIZEOF(4);        /* mrpStatus */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rPort1 */
        rqb_size+=HIF_SER_SIZEOF(2);        /* rPort2 */
        rqb_size+=HIF_SER_SIZEOF(4);        /* adminRole */
        rqb_size+=HIF_SER_SIZEOF(4);        /* operRole */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainBlocked */
        rqb_size+=HIF_SER_SIZEOF(4);        /* domainVlanId */
        rqb_size+=HIF_SER_SIZEOF(2);        /* domainManagerPrio */
        rqb_size+=HIF_SER_SIZEOF(2);        /* domainMrmReactOnLinkChange */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        for(i=0;i<16;i++)                        /* ohaStateInd*/
        {
            HIF_SER_COPY_HTSHM_8((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainUUID[i]);                /* domainUUID */
        }
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.topoCtrlMode,MRP_USR_ENUM_TOPO_CTRL);                /* topoCtrlMode */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.mrpStatus);                /* mrpStatus */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.rPort1);                /* rPort1 */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.rPort2);                /* rPort2 */
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.adminRole,MRP_MIB_ENUM_DOMAIN_ROLE);                /* adminRole */
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.operRole,MRP_MIB_ENUM_DOMAIN_ROLE);                /* operRole */
        HIF_SER_COPY_HTSHM_ENUM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainBlocked,MRP_MIB_ENUM_DOMAIN_BLOCKED);                /* domainBlocked */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainVlanId);                /* domainVlanId */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainManagerPrio);                /* domainManagerPrio */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.state.state_ind.ohaStateInd.domainMrmReactOnLinkChange);                /* domainMrmReactOnLinkChange */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_mrp_serialize_lower(). RQB-Opcode:0x%x is not valid! pRQB(0x%08x)",opcode,ptr_rqb_src+4);
        HIF_FATAL(0);
    }

    *pSerRqbLen = rqb_size;

    HIF_ASSERT(HIF_IS_NOT_NULL(help_ptr)); /*#4*/

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_SERIALIZE(opcode, *ptr_ptr_rqb_dest, rqb_size, help_ptr, "hif_mrp_serialize_lower");

    return HIF_OK;
}

/**
* \brief De-serializes the RQB from the HIF shared memory into the hosts local memory - according to the component ID and OP-code in the RQB.
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] pRqbSrc           - pointer to the serialized RQB in the transfer memory
* @param [out] ppRqbDest        - pointer to the RQB deserialized in the hosts local memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough local memory
*/
LSA_UINT16      hif_mrp_deserialize_upper (
        HIF_SYS_HANDLE hSysDev,
        LSA_VOID* pHifPipeHandle,
        LSA_VOID* pRqbSrc,
        LSA_VOID** ppRqbDest )
{
    LSA_UINT8* help_ptr;
    MRP_RQB_TYPE* new_rqb;
    LSA_OPCODE_TYPE opcode;
    LSA_VOID* ptr_rqb_src = (LSA_VOID*)pRqbSrc;
    MRP_RQB_TYPE** ptr_ptr_rqb_dest = (MRP_RQB_TYPE**)ppRqbDest;
    LSA_RESPONSE_TYPE response = 0;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_ptr_rqb_dest)); /*#17*/
    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src));

    HIF_DESER_GET_OPCODE(ptr_rqb_src, opcode);

    help_ptr = (LSA_UINT8*)ptr_rqb_src + HIF_SER_SIZEOF(4);  /* start deserialization after the original upper RQB pointer */

    new_rqb = (MRP_RQB_TYPE*)hif_get_rqb_id(ptr_rqb_src); /* get orig. upper RQB */
    HIF_PROGRAM_TRACE_03(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_upper() opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,ptr_rqb_src,new_rqb+4);

    if (opcode==MRP_OPC_OPEN_CHANNEL)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==MRP_OPC_CLOSE_CHANNEL)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if  ((opcode==MRP_OPC_PRM_READ)
            ||(opcode==MRP_OPC_PRM_READ_ADMIN_DATA))
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.prm_read.record_data_length,(LSA_UINT32**)&help_ptr);        /* record_data_length */
        if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.ctrl.prm_read.record_data_length > 0 ) /*#22d*/
        {
            help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer-pointer */
            if (HIF_IS_NOT_NULL(new_rqb->args.ctrl.prm_read.record_data)) /*#24*/
            {
                HIF_SER_COPY_SHMTH_BUF(new_rqb->args.ctrl.prm_read.record_data,&help_ptr,new_rqb->args.ctrl.prm_read.record_data_length);        /* record_data */
            }
        }
        else
        {
            help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
        }
    }
    else if (opcode==MRP_OPC_GET_STATUS)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.get_status.domainNameLength,(LSA_UINT32**)&help_ptr);        /* domainNameLength */
        if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.ctrl.get_status.domainNameLength > 0 ) /*#22d*/
        {
            help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer-pointer */
            if (HIF_IS_NOT_NULL(new_rqb->args.ctrl.get_status.pDomainName)) /*#24*/
            {
                HIF_SER_COPY_SHMTH_BUF(new_rqb->args.ctrl.get_status.pDomainName,&help_ptr,new_rqb->args.ctrl.get_status.domainNameLength);        /* pDomainName */
            }
        }
        else
        {
            help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
        }
        HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.ctrl.get_status.operRole,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_DOMAIN_ROLE);        /* operRole */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.get_status.rPort1,(LSA_UINT32**)&help_ptr);        /* rPort1 */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.get_status.rPort2,(LSA_UINT32**)&help_ptr);        /* rPort2 */
        HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.ctrl.get_status.rPort1State,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_RPORT_STATE);        /* rPort1State */
        HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.ctrl.get_status.rPort2State,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_RPORT_STATE);        /* rPort2State */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.get_status.domainState,(LSA_UINT32**)&help_ptr);        /* domainState */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.get_status.domainError,(LSA_UINT32**)&help_ptr);        /* domainError */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.get_status.domainRingOpenCount,(LSA_UINT32**)&help_ptr);        /* domainRingOpenCount */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.get_status.domainLastRingOpenChange,(LSA_UINT32**)&help_ptr);        /* domainLastRingOpenChange */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.get_status.domainRoundTripDelayMax,(LSA_UINT32**)&help_ptr);        /* domainRoundTripDelayMax */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.get_status.domainRoundTripDelayMin,(LSA_UINT32**)&help_ptr);        /* domainRoundTripDelayMin */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.get_status.domainResetRoundTripDelays,(LSA_UINT32**)&help_ptr);        /* domainResetRoundTripDelays */
    }
    else if (opcode==MRP_OPC_SET_STATUS)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==MRP_OPC_STATE_INDICATION)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.state.state_ind.usrStateInd.mrpDiag,(LSA_UINT32**)&help_ptr);        /* mrpDiag */
    }
    else if (opcode==MRP_OPC_RED_STATE_INDICATION)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.initState,(LSA_UINT32**)&help_ptr);        /* initState */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.startState,(LSA_UINT32**)&help_ptr);        /* startState */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.rport1,(LSA_UINT32**)&help_ptr);        /* rport1 */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.rport2,(LSA_UINT32**)&help_ptr);        /* rport2 */
        for(i=0;i<4;i++)                        /* stdbyPorts*/
        {
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.stdbyPorts[i],(LSA_UINT32**)&help_ptr);        /* stdbyPorts */
        }
    }
    else if (opcode==MRP_OPC_RINGSTATE_INDICATION)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        for(i=0;i<16;i++)                        /* domainUUID*/
        {
            HIF_SER_COPY_SHMTH_8(&new_rqb->args.state.state_ind.ohaStateInd.domainUUID[i],(LSA_UINT32**)&help_ptr);        /* domainUUID */
        }
        HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.state.state_ind.ohaStateInd.topoCtrlMode,(LSA_UINT32**)&help_ptr,MRP_USR_ENUM_TOPO_CTRL);        /* topoCtrlMode */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.state.state_ind.ohaStateInd.mrpStatus,(LSA_UINT32**)&help_ptr);        /* mrpStatus */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.rPort1,(LSA_UINT32**)&help_ptr);        /* rPort1 */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.rPort2,(LSA_UINT32**)&help_ptr);        /* rPort2 */
        HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.state.state_ind.ohaStateInd.adminRole,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_DOMAIN_ROLE);        /* adminRole */
        HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.state.state_ind.ohaStateInd.operRole,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_DOMAIN_ROLE);        /* operRole */
        HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.state.state_ind.ohaStateInd.domainBlocked,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_DOMAIN_BLOCKED);        /* domainBlocked */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.state.state_ind.ohaStateInd.domainVlanId,(LSA_UINT32**)&help_ptr);        /* domainVlanId */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.domainManagerPrio,(LSA_UINT32**)&help_ptr);        /* domainManagerPrio */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.domainMrmReactOnLinkChange,(LSA_UINT32**)&help_ptr);        /* domainMrmReactOnLinkChange */
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_mrp_deserialize_upper(). RQB-Opcode:0x%x is not valid! shm_addr(0x%08x)", opcode, ptr_rqb_src);
        HIF_FATAL(0);
    }
    *ptr_ptr_rqb_dest = new_rqb;

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_DESERIALIZE(ptr_rqb_src, opcode, help_ptr, "hif_mrp_deserialize_upper");

    return HIF_OK;
}

/**
* \brief De-serializes the RQB from the HIF shared memory into the hosts local memory - according to the component ID and OP-code in the RQB.
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] pRqbSrc           - pointer to the serialized RQB in the transfer memory
* @param [out] ppRqbDest        - pointer to the RQB deserialized in the hosts local memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough local memory
*/
LSA_UINT16      hif_mrp_deserialize_lower (
        HIF_SYS_HANDLE hSysDev,
        LSA_VOID* pHifPipeHandle,
        LSA_VOID* pRqbSrc,
        LSA_VOID** ppRqbDest )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    MRP_RQB_TYPE* new_rqb  = LSA_NULL;
    LSA_OPCODE_TYPE opcode;
    LSA_VOID* ptr_rqb_src = (LSA_VOID*)pRqbSrc;
    MRP_RQB_TYPE** ptr_ptr_rqb_dest = (MRP_RQB_TYPE**)ppRqbDest;
    LSA_UINT32 rqb_size = 0;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_ptr_rqb_dest)); /*#17*/
    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src));

    HIF_DESER_GET_OPCODE(ptr_rqb_src, opcode);

    if (opcode==MRP_OPC_OPEN_CHANNEL)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(MRP_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(MRP_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_SYS_PATH_SHMTH(&new_rqb->args.channel.open.sys_path,(LSA_UINT32**)&help_ptr);            /* sys_path */
        }
    }
    else if (opcode==MRP_OPC_CLOSE_CHANNEL)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(MRP_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(MRP_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
        }
    }
    else if  ((opcode==MRP_OPC_PRM_READ)
            ||(opcode==MRP_OPC_PRM_READ_ADMIN_DATA))
    {
        /* calculate rqb-size */
        rqb_size=sizeof(MRP_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(MRP_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.prm_read.slot_number,(LSA_UINT32**)&help_ptr);            /* slot_number */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.prm_read.subslot_number,(LSA_UINT32**)&help_ptr);            /* subslot_number */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.prm_read.edd_port_id,(LSA_UINT32**)&help_ptr);            /* edd_port_id */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.prm_read.record_index,(LSA_UINT32**)&help_ptr);            /* record_index */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.prm_read.record_data_length,(LSA_UINT32**)&help_ptr);            /* record_data_length */
        }
    }
    else if (opcode==MRP_OPC_GET_STATUS)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(MRP_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(MRP_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.get_status.mrpInstance,(LSA_UINT32**)&help_ptr);            /* mrpInstance */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.get_status.domainNameLength,(LSA_UINT32**)&help_ptr);            /* domainNameLength */
            if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.ctrl.get_status.domainNameLength > 0 ) /*#22d*/
            {
                help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer pointer */
                HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb->args.ctrl.get_status.pDomainName,new_rqb->args.ctrl.get_status.domainNameLength, LSA_COMP_ID_MRP, HIF_MEM_TYPE_BUFFER );
                HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() allocate buffer buffer_size(%d) opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",new_rqb->args.ctrl.get_status.domainNameLength,opcode,help_ptr,new_rqb+4);
                if (HIF_IS_NOT_NULL(new_rqb->args.ctrl.get_status.pDomainName)) /*#23*/
                {
                    HIF_SER_COPY_SHMTH_BUF(new_rqb->args.ctrl.get_status.pDomainName,&help_ptr,new_rqb->args.ctrl.get_status.domainNameLength);            /* pDomainName */
                }
                else
                {
                    return HIF_ERR_RESOURCE;
                }
            }
            else
            {
                new_rqb->args.ctrl.get_status.pDomainName = LSA_NULL; /* set data buffer pointer to NULL */
                help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
            }
        }
    }
    else if (opcode==MRP_OPC_SET_STATUS)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(MRP_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(MRP_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.ctrl.set_status.mrpInstance,(LSA_UINT32**)&help_ptr);            /* mrpInstance */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.ctrl.set_status.domainResetRoundTripDelays,(LSA_UINT32**)&help_ptr);            /* domainResetRoundTripDelays */
        }
    }
    else if (opcode==MRP_OPC_STATE_INDICATION)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(MRP_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(MRP_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.usrStateInd.mrpInstance,(LSA_UINT32**)&help_ptr);            /* mrpInstance */
        }
    }
    else if (opcode==MRP_OPC_RED_STATE_INDICATION)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(MRP_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(MRP_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.mrpInstance,(LSA_UINT32**)&help_ptr);            /* mrpInstance */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.initState,(LSA_UINT32**)&help_ptr);            /* initState */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.startState,(LSA_UINT32**)&help_ptr);            /* startState */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.rport1,(LSA_UINT32**)&help_ptr);            /* rport1 */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.rport2,(LSA_UINT32**)&help_ptr);            /* rport2 */
            for(i=0;i<4;i++)                                    /* stdbyPorts*/
            {
                HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.redStateInd.stdbyPorts[i],(LSA_UINT32**)&help_ptr);            /* stdbyPorts */
            }
        }
    }
    else if (opcode==MRP_OPC_RINGSTATE_INDICATION)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(MRP_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_MRP, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_mrp_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(MRP_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.mrpInstance,(LSA_UINT32**)&help_ptr);            /* mrpInstance */
            for(i=0;i<16;i++)                                    /* domainUUID*/
            {
                HIF_SER_COPY_SHMTH_8(&new_rqb->args.state.state_ind.ohaStateInd.domainUUID[i],(LSA_UINT32**)&help_ptr);            /* domainUUID */
            }
            HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.state.state_ind.ohaStateInd.topoCtrlMode,(LSA_UINT32**)&help_ptr,MRP_USR_ENUM_TOPO_CTRL);            /* topoCtrlMode */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.state.state_ind.ohaStateInd.mrpStatus,(LSA_UINT32**)&help_ptr);            /* mrpStatus */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.rPort1,(LSA_UINT32**)&help_ptr);            /* rPort1 */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.rPort2,(LSA_UINT32**)&help_ptr);            /* rPort2 */
            HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.state.state_ind.ohaStateInd.adminRole,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_DOMAIN_ROLE);            /* adminRole */
            HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.state.state_ind.ohaStateInd.operRole,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_DOMAIN_ROLE);            /* operRole */
            HIF_SER_COPY_SHMTH_ENUM(&new_rqb->args.state.state_ind.ohaStateInd.domainBlocked,(LSA_UINT32**)&help_ptr,MRP_MIB_ENUM_DOMAIN_BLOCKED);            /* domainBlocked */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.state.state_ind.ohaStateInd.domainVlanId,(LSA_UINT32**)&help_ptr);            /* domainVlanId */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.domainManagerPrio,(LSA_UINT32**)&help_ptr);            /* domainManagerPrio */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.state.state_ind.ohaStateInd.domainMrmReactOnLinkChange,(LSA_UINT32**)&help_ptr);            /* domainMrmReactOnLinkChange */
        }
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_mrp_deserialize_lower(). RQB-Opcode:0x%x is not valid! shm_addr(0x%08x)", opcode, ptr_rqb_src);
        HIF_FATAL(0);
    }
    HIF_RQB_SET_COMP_ID(new_rqb, LSA_COMP_ID_MRP);            /* set comp id */
    *ptr_ptr_rqb_dest = new_rqb;

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_DESERIALIZE(ptr_rqb_src, opcode, help_ptr, "hif_mrp_deserialize_lower");

    return HIF_OK;
}


//lint -restore -e506
//lint -restore -e774

#endif /* of HIF_CFG_USE_MRP */
#if defined(TOOL_CHAIN_MICROSOFT) /* Microsoft Visual C++ */
#pragma component(browser, on, references)
#endif
/*****************************************************************************/
/* End of File                                                               */
/*****************************************************************************/
