/*****************************************************************************/
/*  Copyright (C) 2019 Siemens Aktiengesellschaft. All rights reserved.      */
/*****************************************************************************/
/*  This program is protected by German copyright law and international      */
/*  treaties. The use of this software including but not limited to its      */
/*  Source Code is subject to restrictions as agreed in the license          */
/*  agreement between you and Siemens.                                       */
/*  Copying or distribution is not allowed unless expressly permitted        */
/*  according to your license agreement with Siemens.                        */
/*****************************************************************************/
/*                                                                           */
/*  P r o j e c t         &P: PROFINET IO Runtime Software              :P&  */
/*                                                                           */
/*  P a c k a g e         &W: PROFINET IO Runtime Software              :W&  */
/*                                                                           */
/*  C o m p o n e n t     &C: HIF (Host Interface)                      :C&  */
/*                                                                           */
/*  F i l e               &F: hif_ser_hsa.c                             :F&  */
/*                                                                           */
/*  V e r s i o n         &V: BC_PNRUN_P07.01.00.00_00.02.00.15         :V&  */
/*                                                                           */
/*  D a t e  (YYYY-MM-DD) &D: 2019-08-05                                :D&  */
/*                                                                           */
/*****************************************************************************/
/*                                                                           */
/*  D e s c r i p t i o n :                                                  */
/*                                                                           */
/*  Automatically generated with HIF Code Generator v2.4.1                   */
/*                                                                           */
/*                                                                           */
/*  !!!ATTENTION: Do not edit this file.                                     */
/*                Please use the HIF Code Generator to generate this file.   */
/*                                                                           */
/*  The hash value was automatically calculated by HIF Code Generator!       */
/*  HASH-VALUE: WVx4kLPRHkO9BXygw6tAD56Adya8CH1PPjKNy0rzyjI=                 */
/*****************************************************************************/

#if defined(TOOL_CHAIN_MICROSOFT) /* Microsoft Visual C++ */
#pragma component(browser, off, references)
#endif

#define LTRC_ACT_MODUL_ID   117
#define HIF_MODULE_ID       LTRC_ACT_MODUL_ID

#include "hif_int.h"      

/// @cond PREVENT_DOXYGEN
HIF_FILE_SYSTEM_EXTENSION(HIF_MODULE_ID)

/// @endcond
#if ( (HIF_CFG_COMPILE_SERIALIZATION == 1) && (HIF_CFG_USE_HSA == 1) )


//lint -save -e506
// Warning 506: Constant value Boolean; It is expected that these issues are optimized while compilation of source code.
//lint -save -e774
// Warning 774: If always evaluates to True; It is expected that these issues are optimized while compilation of source code.

/* Prototypes */


/* Helper Functions */

/**
* \brief Function serializes the RQB to the HIF shared memory according to the component ID and OP-code in the RQB. 
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] hShmPool          - pool handle for the transfer memory
* @param [in] pRqbSrc           - pointer to the RQB that is serialized
* @param [out] ppRqbDest        - pointer to the serialized RQB in the HIF transfer memory
* @param [out] pSerRqbLen       - total length of the serialized RQB in the transfer memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough memory available in the transfer memory
*/
LSA_UINT16  hif_hsa_serialize_upper (
    HIF_SYS_HANDLE hSysDev,
    LSA_VOID*      pHifPipeHandle,
    LSA_INT        hShmPool,
    LSA_VOID*      pRqbSrc,
    LSA_VOID**     ppRqbDest,
    LSA_UINT32*    pSerRqbLen )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    LSA_UINT32 rqb_size = 0;
    LSA_OPCODE_TYPE opcode;
    HSA_RQB_TYPE* ptr_rqb_src = (HSA_RQB_TYPE*)pRqbSrc;
    LSA_VOID** ptr_ptr_rqb_dest = ppRqbDest;
    
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src)); /*#5*/
    opcode=HIF_RQB_GET_OPCODE(ptr_rqb_src);

    if (opcode==HSA_OPC_OPEN_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_SYS_PATH_TYPE();        /* sys_path */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_SYS_PATH_HTSHM((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.channel.sys_path);                /* sys_path */
    }
    else if (opcode==HSA_OPC_CLOSE_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
    }
    else if (opcode==HSA_OPC_START_INSTANCE)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* role */
        rqb_size+=HIF_SER_SIZEOF(4);        /* maxNumberOfFramesPerCycle */
        rqb_size+=HIF_SER_SIZEOF(4);        /* actNumberOfFramesPerCycle */
        rqb_size+=HIF_SER_SIZEOF(2);        /* sendMode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* frameLength */
        rqb_size+=HIF_SER_SIZEOF(2);        /* sendPrio */
        rqb_size+=HIF_SER_SIZEOF(2);        /* sendPrioRatio */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.start.role);                /* role */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.start.maxNumberOfFramesPerCycle);                /* maxNumberOfFramesPerCycle */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.start.client.actNumberOfFramesPerCycle);                /* actNumberOfFramesPerCycle */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.start.client.sendMode);                /* sendMode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.start.client.frameLength);                /* frameLength */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.start.client.sendPrio);                /* sendPrio */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.start.client.sendPrioRatio);                /* sendPrioRatio */
    }
    else if (opcode==HSA_OPC_STOP_INSTANCE)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* instanceHandle */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.stop.instanceHandle);                /* instanceHandle */
    }
    else if (opcode==HSA_OPC_GET_STATISTICS)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
    }
    else if (opcode==HSA_OPC_SEND_SINGLE_FRAME)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* ringPort */
        rqb_size+=HIF_SER_SIZEOF(4);        /* frameLength */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "pFramebuf" pointer itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.send.pFramebuf /* #8*/))
        {
            rqb_size+=HIF_SER_SIZEOF_BUF(ptr_rqb_src->args.send.frameLength);        /* size of: pFramebuf */
        }
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.send.ringPort);                /* ringPort */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.send.frameLength);                /* frameLength */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.send.pFramebuf);        /* pointer info itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.send.pFramebuf /*#11*/))
        {
            HIF_SER_COPY_HTSHM_BUFFER(&help_ptr,ptr_rqb_src->args.send.pFramebuf,ptr_rqb_src->args.send.frameLength, hSysDev);        /* pFramebuf */
        }
    }
    else if (opcode==HSA_OPC_RECEIVE_SINGLE_FRAME)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF(2);        /* ringPort */
        rqb_size+=HIF_SER_SIZEOF(4);        /* frameLength */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "pFramebuf" pointer itself */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.recv.ringPort);                /* ringPort */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.recv.frameLength);                /* frameLength */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.recv.pFramebuf);        /* pointer info itself */
    }
    else if (opcode==HSA_OPC_CANCEL_RECEIVE)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_upper() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src);                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_hsa_serialize_upper(). RQB-Opcode:0x%x is not valid! pRQB(0x%08x)",opcode,ptr_rqb_src+4);
        HIF_FATAL(0);
    }

    *pSerRqbLen = rqb_size;

    HIF_ASSERT(HIF_IS_NOT_NULL(help_ptr)); /*#4*/

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_SERIALIZE(opcode, *ptr_ptr_rqb_dest, rqb_size, help_ptr, "hif_hsa_serialize_upper");

    return HIF_OK;
}

/**
* \brief Function serializes the RQB to the HIF shared memory according to the component ID and OP-code in the RQB. 
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] hShmPool          - pool handle for the transfer memory
* @param [in] pRqbSrc           - pointer to the RQB that is serialized
* @param [out] ppRqbDest        - pointer to the serialized RQB in the HIF transfer memory
* @param [out] pSerRqbLen       - total length of the serialized RQB in the transfer memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough memory available in the transfer memory
*/
LSA_UINT16  hif_hsa_serialize_lower (
    HIF_SYS_HANDLE hSysDev,
    LSA_VOID*      pHifPipeHandle,
    LSA_INT        hShmPool,
    LSA_VOID*      pRqbSrc,
    LSA_VOID**     ppRqbDest,
    LSA_UINT32*    pSerRqbLen )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    LSA_UINT32 rqb_size = 0;
    LSA_OPCODE_TYPE opcode;
    HSA_RQB_TYPE* ptr_rqb_src = (HSA_RQB_TYPE*)pRqbSrc;
    LSA_VOID** ptr_ptr_rqb_dest = ppRqbDest;
    LSA_UINT16 freeRes;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src)); /*#5*/
    opcode=HIF_RQB_GET_OPCODE(ptr_rqb_src);

    if (opcode==HSA_OPC_OPEN_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==HSA_OPC_CLOSE_CHANNEL)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==HSA_OPC_START_INSTANCE)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(2);        /* instanceHandle */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.start.instanceHandle);                /* instanceHandle */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==HSA_OPC_STOP_INSTANCE)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==HSA_OPC_GET_STATISTICS)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(4);        /* outFrameLow */
        rqb_size+=HIF_SER_SIZEOF(4);        /* outFrameHigh */
        rqb_size+=HIF_SER_SIZEOF(4);        /* inFrameLow */
        rqb_size+=HIF_SER_SIZEOF(4);        /* inFrameHigh */
        rqb_size+=HIF_SER_SIZEOF(4);        /* inDuplicateLow */
        rqb_size+=HIF_SER_SIZEOF(4);        /* inDuplicateHigh */
        for(i=0;i<HSA_MAX_PORT;i++)        /* port*/
        {
            rqb_size+=HIF_SER_SIZEOF(4);            /* outFrameLow */
            rqb_size+=HIF_SER_SIZEOF(4);            /* outFrameHigh */
            rqb_size+=HIF_SER_SIZEOF(4);            /* inFrameLow */
            rqb_size+=HIF_SER_SIZEOF(4);            /* inFrameHigh */
            rqb_size+=HIF_SER_SIZEOF(4);            /* LowPassedLow */
            rqb_size+=HIF_SER_SIZEOF(4);            /* LowPassedHigh */
            rqb_size+=HIF_SER_SIZEOF(4);            /* HighPassedLow */
            rqb_size+=HIF_SER_SIZEOF(4);            /* HighPassedHigh */
        }
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.outFrameLow);                /* outFrameLow */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.outFrameHigh);                /* outFrameHigh */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.inFrameLow);                /* inFrameLow */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.inFrameHigh);                /* inFrameHigh */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.inDuplicateLow);                /* inDuplicateLow */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.inDuplicateHigh);                /* inDuplicateHigh */
        for(i=0;i<HSA_MAX_PORT;i++)                                /* port*/
        {
            HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.port[i].outFrameLow);                        /* outFrameLow */
            HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.port[i].outFrameHigh);                        /* outFrameHigh */
            HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.port[i].inFrameLow);                        /* inFrameLow */
            HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.port[i].inFrameHigh);                        /* inFrameHigh */
            HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.port[i].LowPassedLow);                        /* LowPassedLow */
            HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.port[i].LowPassedHigh);                        /* LowPassedHigh */
            HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.port[i].HighPassedLow);                        /* HighPassedLow */
            HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.statistics.port[i].HighPassedHigh);                        /* HighPassedHigh */
        }

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==HSA_OPC_SEND_SINGLE_FRAME)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.send.pFramebuf)) /*#13*/
        {
            freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
            HIF_FREE_LOCAL_MEMORY(&freeRes, ptr_rqb_src->args.send.pFramebuf, LSA_COMP_ID_HSA, HIF_MEM_TYPE_BUFFER, hSysDev);
            if (freeRes != LSA_RET_OK)
            {
                return HIF_ERR_RESOURCE;
            }
        }
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==HSA_OPC_RECEIVE_SINGLE_FRAME)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        rqb_size+=HIF_SER_SIZEOF(2);        /* ringPort */
        rqb_size+=HIF_SER_SIZEOF(4);        /* serialize "pFramebuf" pointer itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.recv.pFramebuf /* #8*/))
        {
            rqb_size+=HIF_SER_SIZEOF_BUF(ptr_rqb_src->args.recv.frameLength);        /* size of: pFramebuf */
        }
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */
        HIF_SER_COPY_HTSHM_16((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.recv.ringPort);                /* ringPort */
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,ptr_rqb_src->args.recv.pFramebuf);        /* pointer info itself */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.recv.pFramebuf /*#11*/))
        {
            HIF_SER_COPY_HTSHM_BUFFER(&help_ptr,ptr_rqb_src->args.recv.pFramebuf,ptr_rqb_src->args.recv.frameLength, hSysDev);        /* pFramebuf */
        }

        /* Delete lower RQB after lower serialization */
        if (HIF_IS_NOT_NULL(ptr_rqb_src->args.recv.pFramebuf)) /*#13*/
        {
            freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
            HIF_FREE_LOCAL_MEMORY(&freeRes, ptr_rqb_src->args.recv.pFramebuf, LSA_COMP_ID_HSA, HIF_MEM_TYPE_BUFFER, hSysDev);
            if (freeRes != LSA_RET_OK)
            {
                return HIF_ERR_RESOURCE;
            }
        }
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else if (opcode==HSA_OPC_CANCEL_RECEIVE)
    {
        rqb_size+=HIF_SER_SIZEOF(4);        /* original upper RQB pointer */
        rqb_size+=HIF_SER_SIZEOF_OPCODE_TYPE();        /* _opcode */
        rqb_size+=HIF_SER_SIZEOF_RESPONSE_TYPE();        /* _response */
        help_ptr = hif_mem_ring_pool_alloc(rqb_size, hShmPool);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_serialize_lower() opc(%d) rqb_size_shm(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,ptr_rqb_src);

        if (HIF_IS_NULL(help_ptr))
        {
            return HIF_ERR_RESOURCE;
        }

        *ptr_ptr_rqb_dest = help_ptr;
        HIF_SER_COPY_HTSHM_32((LSA_UINT32**)&help_ptr,*((LSA_UINT32*)ptr_rqb_src-1));                /* original upper RQB pointer */

        HIF_SER_OPCODE_HTSHM((LSA_UINT32**)&help_ptr,opcode);                /* _opcode */
        HIF_SER_RESPONSE_HTSHM((LSA_UINT32**)&help_ptr,HIF_RQB_GET_RESPONSE(ptr_rqb_src));                /* _response */

        /* Delete lower RQB after lower serialization */
        freeRes = LSA_RET_ERR_RESOURCE; /* preset negative */
        HIF_FREE_LOCAL_MEMORY(&freeRes, (LSA_UINT8*)ptr_rqb_src-HIF_SER_SIZEOF(4), LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        if (freeRes != LSA_RET_OK)
        {
            return HIF_ERR_RESOURCE;
        }
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_hsa_serialize_lower(). RQB-Opcode:0x%x is not valid! pRQB(0x%08x)",opcode,ptr_rqb_src+4);
        HIF_FATAL(0);
    }

    *pSerRqbLen = rqb_size;

    HIF_ASSERT(HIF_IS_NOT_NULL(help_ptr)); /*#4*/

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_SERIALIZE(opcode, *ptr_ptr_rqb_dest, rqb_size, help_ptr, "hif_hsa_serialize_lower");

    return HIF_OK;
}

/**
* \brief De-serializes the RQB from the HIF shared memory into the hosts local memory - according to the component ID and OP-code in the RQB.
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] pRqbSrc           - pointer to the serialized RQB in the transfer memory
* @param [out] ppRqbDest        - pointer to the RQB deserialized in the hosts local memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough local memory
*/
LSA_UINT16      hif_hsa_deserialize_upper (
        HIF_SYS_HANDLE hSysDev,
        LSA_VOID* pHifPipeHandle,
        LSA_VOID* pRqbSrc,
        LSA_VOID** ppRqbDest )
{
    LSA_UINT8* help_ptr;
    HSA_RQB_TYPE* new_rqb;
    LSA_OPCODE_TYPE opcode;
    LSA_VOID* ptr_rqb_src = (LSA_VOID*)pRqbSrc;
    HSA_RQB_TYPE** ptr_ptr_rqb_dest = (HSA_RQB_TYPE**)ppRqbDest;
    LSA_RESPONSE_TYPE response = 0;
    LSA_UINT32 i=0;
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_ptr_rqb_dest)); /*#17*/
    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src));

    HIF_DESER_GET_OPCODE(ptr_rqb_src, opcode);

    help_ptr = (LSA_UINT8*)ptr_rqb_src + HIF_SER_SIZEOF(4);  /* start deserialization after the original upper RQB pointer */

    new_rqb = (HSA_RQB_TYPE*)hif_get_rqb_id(ptr_rqb_src); /* get orig. upper RQB */
    HIF_PROGRAM_TRACE_03(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_upper() opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,ptr_rqb_src,new_rqb+4);

    if (opcode==HSA_OPC_OPEN_CHANNEL)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==HSA_OPC_CLOSE_CHANNEL)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==HSA_OPC_START_INSTANCE)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.start.instanceHandle,(LSA_UINT32**)&help_ptr);        /* instanceHandle */
    }
    else if (opcode==HSA_OPC_STOP_INSTANCE)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==HSA_OPC_GET_STATISTICS)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.outFrameLow,(LSA_UINT32**)&help_ptr);        /* outFrameLow */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.outFrameHigh,(LSA_UINT32**)&help_ptr);        /* outFrameHigh */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.inFrameLow,(LSA_UINT32**)&help_ptr);        /* inFrameLow */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.inFrameHigh,(LSA_UINT32**)&help_ptr);        /* inFrameHigh */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.inDuplicateLow,(LSA_UINT32**)&help_ptr);        /* inDuplicateLow */
        HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.inDuplicateHigh,(LSA_UINT32**)&help_ptr);        /* inDuplicateHigh */
        for(i=0;i<HSA_MAX_PORT;i++)                        /* port*/
        {
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.port[i].outFrameLow,(LSA_UINT32**)&help_ptr);            /* outFrameLow */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.port[i].outFrameHigh,(LSA_UINT32**)&help_ptr);            /* outFrameHigh */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.port[i].inFrameLow,(LSA_UINT32**)&help_ptr);            /* inFrameLow */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.port[i].inFrameHigh,(LSA_UINT32**)&help_ptr);            /* inFrameHigh */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.port[i].LowPassedLow,(LSA_UINT32**)&help_ptr);            /* LowPassedLow */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.port[i].LowPassedHigh,(LSA_UINT32**)&help_ptr);            /* LowPassedHigh */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.port[i].HighPassedLow,(LSA_UINT32**)&help_ptr);            /* HighPassedLow */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.statistics.port[i].HighPassedHigh,(LSA_UINT32**)&help_ptr);            /* HighPassedHigh */
        }
    }
    else if (opcode==HSA_OPC_SEND_SINGLE_FRAME)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else if (opcode==HSA_OPC_RECEIVE_SINGLE_FRAME)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
        HIF_SER_COPY_SHMTH_16(&new_rqb->args.recv.ringPort,(LSA_UINT32**)&help_ptr);        /* ringPort */
        if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.recv.frameLength > 0 ) /*#22d*/
        {
            help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer-pointer */
            if (HIF_IS_NOT_NULL(new_rqb->args.recv.pFramebuf)) /*#24*/
            {
                HIF_SER_COPY_SHMTH_BUF(new_rqb->args.recv.pFramebuf,&help_ptr,new_rqb->args.recv.frameLength);        /* pFramebuf */
            }
        }
        else
        {
            help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
        }
    }
    else if (opcode==HSA_OPC_CANCEL_RECEIVE)
    {

        /* restore the Upper RQB */
        HIF_RQB_SET_OPCODE(new_rqb,opcode);                /* _opcode */
        help_ptr+=4;                /* skip opcode on shared-mem */
        HIF_SER_RESPONSE_SHMTH(&response,(LSA_UINT32**)&help_ptr);                /* _response */
        HIF_RQB_SET_RESPONSE(new_rqb,response);                                /* _response */
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_hsa_deserialize_upper(). RQB-Opcode:0x%x is not valid! shm_addr(0x%08x)", opcode, ptr_rqb_src);
        HIF_FATAL(0);
    }
    *ptr_ptr_rqb_dest = new_rqb;

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_DESERIALIZE(ptr_rqb_src, opcode, help_ptr, "hif_hsa_deserialize_upper");

    return HIF_OK;
}

/**
* \brief De-serializes the RQB from the HIF shared memory into the hosts local memory - according to the component ID and OP-code in the RQB.
*
* @param [in] hSysDev           - system handle 
* @param [in] pHifPipeHandle    - pipe handle
* @param [in] pRqbSrc           - pointer to the serialized RQB in the transfer memory
* @param [out] ppRqbDest        - pointer to the RQB deserialized in the hosts local memory
*
* @return HIF_OK                - success
* @return HIF_ERR_RESOURCE      - Not enough local memory
*/
LSA_UINT16      hif_hsa_deserialize_lower (
        HIF_SYS_HANDLE hSysDev,
        LSA_VOID* pHifPipeHandle,
        LSA_VOID* pRqbSrc,
        LSA_VOID** ppRqbDest )
{
    LSA_UINT8* help_ptr = LSA_NULL;
    HSA_RQB_TYPE* new_rqb  = LSA_NULL;
    LSA_OPCODE_TYPE opcode;
    LSA_VOID* ptr_rqb_src = (LSA_VOID*)pRqbSrc;
    HSA_RQB_TYPE** ptr_ptr_rqb_dest = (HSA_RQB_TYPE**)ppRqbDest;
    LSA_UINT32 rqb_size = 0;
    
    LSA_UNUSED_ARG(hSysDev);
    LSA_UNUSED_ARG(pHifPipeHandle);

    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_ptr_rqb_dest)); /*#17*/
    HIF_ASSERT(HIF_IS_NOT_NULL(ptr_rqb_src));

    HIF_DESER_GET_OPCODE(ptr_rqb_src, opcode);

    if (opcode==HSA_OPC_OPEN_CHANNEL)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(HSA_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(HSA_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_SYS_PATH_SHMTH(&new_rqb->args.channel.sys_path,(LSA_UINT32**)&help_ptr);            /* sys_path */
        }
    }
    else if (opcode==HSA_OPC_CLOSE_CHANNEL)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(HSA_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(HSA_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
        }
    }
    else if (opcode==HSA_OPC_START_INSTANCE)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(HSA_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(HSA_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.start.role,(LSA_UINT32**)&help_ptr);            /* role */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.start.maxNumberOfFramesPerCycle,(LSA_UINT32**)&help_ptr);            /* maxNumberOfFramesPerCycle */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.start.client.actNumberOfFramesPerCycle,(LSA_UINT32**)&help_ptr);            /* actNumberOfFramesPerCycle */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.start.client.sendMode,(LSA_UINT32**)&help_ptr);            /* sendMode */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.start.client.frameLength,(LSA_UINT32**)&help_ptr);            /* frameLength */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.start.client.sendPrio,(LSA_UINT32**)&help_ptr);            /* sendPrio */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.start.client.sendPrioRatio,(LSA_UINT32**)&help_ptr);            /* sendPrioRatio */
        }
    }
    else if (opcode==HSA_OPC_STOP_INSTANCE)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(HSA_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(HSA_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.stop.instanceHandle,(LSA_UINT32**)&help_ptr);            /* instanceHandle */
        }
    }
    else if (opcode==HSA_OPC_GET_STATISTICS)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(HSA_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(HSA_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
        }
    }
    else if (opcode==HSA_OPC_SEND_SINGLE_FRAME)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(HSA_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(HSA_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.send.ringPort,(LSA_UINT32**)&help_ptr);            /* ringPort */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.send.frameLength,(LSA_UINT32**)&help_ptr);            /* frameLength */
            if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.send.frameLength > 0 ) /*#22d*/
            {
                help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer pointer */
                HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb->args.send.pFramebuf,new_rqb->args.send.frameLength, LSA_COMP_ID_HSA, HIF_MEM_TYPE_BUFFER );
                HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() allocate buffer buffer_size(%d) opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",new_rqb->args.send.frameLength,opcode,help_ptr,new_rqb+4);
                if (HIF_IS_NOT_NULL(new_rqb->args.send.pFramebuf)) /*#23*/
                {
                    HIF_SER_COPY_SHMTH_BUF(new_rqb->args.send.pFramebuf,&help_ptr,new_rqb->args.send.frameLength);            /* pFramebuf */
                }
                else
                {
                    return HIF_ERR_RESOURCE;
                }
            }
            else
            {
                new_rqb->args.send.pFramebuf = LSA_NULL; /* set data buffer pointer to NULL */
                help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
            }
        }
    }
    else if (opcode==HSA_OPC_RECEIVE_SINGLE_FRAME)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(HSA_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(HSA_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
            HIF_SER_COPY_SHMTH_16(&new_rqb->args.recv.ringPort,(LSA_UINT32**)&help_ptr);            /* ringPort */
            HIF_SER_COPY_SHMTH_32(&new_rqb->args.recv.frameLength,(LSA_UINT32**)&help_ptr);            /* frameLength */
            if (HIF_IS_NOT_NULL_U32_REF_BY_PTR(help_ptr) && new_rqb->args.recv.frameLength > 0 ) /*#22d*/
            {
                help_ptr+=HIF_SER_SIZEOF(4); /* skip buffer pointer */
                HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb->args.recv.pFramebuf,new_rqb->args.recv.frameLength, LSA_COMP_ID_HSA, HIF_MEM_TYPE_BUFFER );
                HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() allocate buffer buffer_size(%d) opc(%d) shm_addr(0x%08x) pRQB(0x%08x)",new_rqb->args.recv.frameLength,opcode,help_ptr,new_rqb+4);
                if (HIF_IS_NULL(new_rqb->args.recv.pFramebuf)) /*#23a*/
                {
                    /* Check allocated buffer, but do not copy anything (copydir='CNF')*/
                    return HIF_ERR_RESOURCE;
                }
            }
            else
            {
                new_rqb->args.recv.pFramebuf = LSA_NULL; /* set data buffer pointer to NULL */
                help_ptr+=HIF_SER_SIZEOF(4);          /* skip buffer-pointer */
            }
        }
    }
    else if (opcode==HSA_OPC_CANCEL_RECEIVE)
    {
        /* calculate rqb-size */
        rqb_size=sizeof(HSA_RQB_TYPE) + HIF_SER_SIZEOF(4);        /* RQB-size + original upper RQB pointer */
        help_ptr = (LSA_UINT8*)ptr_rqb_src;

        HIF_ALLOC_LOCAL_MEM((LSA_VOID**)&new_rqb, rqb_size, LSA_COMP_ID_HSA, HIF_MEM_TYPE_RQB);
        HIF_PROGRAM_TRACE_04(0,LSA_TRACE_LEVEL_NOTE_LOW,"hif_hsa_deserialize_lower() opc(%d) rqb_size(%d) shm_addr(0x%08x) pRQB(0x%08x)",opcode,rqb_size,help_ptr,new_rqb+4);
        if (HIF_IS_NULL(new_rqb))
        {
            return HIF_ERR_RESOURCE;
        }
        else
        {
            HIF_SER_COPY_SHMTH_32((LSA_UINT32*)new_rqb,(LSA_UINT32**)&help_ptr);            /* orig. upper RQB pointer */
            new_rqb=(HSA_RQB_TYPE*)HIF_CAST_TO_VOID_PTR((LSA_UINT8*)new_rqb+HIF_SER_SIZEOF(4));                                     /* real lower rqb src without orig. upper RQB pointer */
            *ptr_ptr_rqb_dest = new_rqb;                                    /* return real lower rqb src without orig. upper RQB pointer */

            /* restore Lower RQB */
            HIF_RQB_SET_OPCODE(new_rqb,opcode);                        /* _opcode */
            help_ptr+=4;                        /* skip opcode on shared-mem */
        }
    }
    else
    {
        HIF_PROGRAM_TRACE_02(0,LSA_TRACE_LEVEL_FATAL,"hif_hsa_deserialize_lower(). RQB-Opcode:0x%x is not valid! shm_addr(0x%08x)", opcode, ptr_rqb_src);
        HIF_FATAL(0);
    }
    HIF_RQB_SET_COMP_ID(new_rqb, LSA_COMP_ID_HSA);            /* set comp id */
    *ptr_ptr_rqb_dest = new_rqb;

    /* Check for overwrite */
    HIF_SHM_CHECK_OVERWRITE_DESERIALIZE(ptr_rqb_src, opcode, help_ptr, "hif_hsa_deserialize_lower");

    return HIF_OK;
}


//lint -restore -e506
//lint -restore -e774

#endif /* of HIF_CFG_USE_HSA */
#if defined(TOOL_CHAIN_MICROSOFT) /* Microsoft Visual C++ */
#pragma component(browser, on, references)
#endif
/*****************************************************************************/
/* End of File                                                               */
/*****************************************************************************/
